mmyster/feature/functional tests
leka/LekaOS pull request #1020
Opened 2022-09-13 12:02 UTC by MMyster

- :white_check_mark: (spike): Add lk_boost_ut
- :white_check_mark: (spike): Update lk_boost_ut
- :chart_with_upward_trend: (tools): check boost ut status
- :chart_with_upward_trend: (tools): Update - check boost ut status
- :white_check_mark: (functional): add some test templates

2022-09-19 19:11 UTC, ladislas requested changes
very interesting PR! 👍 I've made a lot of comments for small typos or naming and a few suggestions to improve the structure

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +        saving_default_filename + saving_extension_txt
`saving` means `épargne`, not `saved file`

what you can use instead is `result`, which gives you:

```suggestion
    result_directory = "./fs/usr/test/"
    result_extension = ".txt"
    result_default_filename = "file_saving"
    result_path = result_directory + \
        result_default_filename + result_extension
```

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +            stem, ext = os.path.splitext(base)
what does `stem` stand for?

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +    def generate_saving_file(self):
```suggestion
    def generate_result_file(self):
```

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +    def edit_saving_file(self, data):
```suggestion
    def edit_result_file(self, data):
```

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +    def print_saving_file(self, color=Fore.RED):
```suggestion
    def print_result_file(self, color=Fore.RED):
```

also the color must be the one from the output, so no need for `color=Fore.RED`

```suggestion
    def print_result_file(self):
```

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +            os.remove(f)
why `static`? consider moving this function out of the class to avoid static

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +        saving_default_filename + saving_extension_txt
these could also be defined globally if needed

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +            return None
I find nested function definitions hard to read. 

Those are very related, they could be moved to their own class

2022-09-19 19:11 UTC, ladislas commented on tools/run_functional_tests.py
> +def list_files_bin():
```suggestion
def list_bin_files():
```

2022-09-20 08:42 UTC, MMyster commented on tools/run_functional_tests.py
> +            stem, ext = os.path.splitext(base)
It's filename stripped of its extension

2022-10-21 15:41 UTC, YannLocatelli commented on tools/run_functional_tests.py
> +            self.path+" 0x08000000' -c exit"
This script has a lot of operation and it's hard to review as it is.

Just a comment, some information and command as `CMD_FLASH` should have same source.

2022-10-24 12:51 UTC, ladislas commented on tools/run_functional_tests.py
> +#!/usr/bin/env python3
not sure for now, we'll see in the future PRs adding CI support what we'll do

2022-10-24 13:17 UTC, MMyster commented on tests/functional/sources/QDAC/suite_qdac.cpp
> +		expect(data == ret) << "Failed to read Channel A";
Yes, it is. But as I said, it is currently not functional. I was planning to take a look at it later or delete it by default.

2022-10-24 16:48 UTC, ladislas commented
closed by #1079

2022-10-24 16:48 UTC, closed without merging