ladislas+hugo/feature/quit activity mode
leka/LekaOS pull request #1062
Opened 2022-10-13 12:16 UTC by ladislas

- :construction: (wip): Use dice roll to go in classic mode
- :construction: (WIP): Add delay for start/stop

2022-10-20 10:45 UTC, ladislas reviewed
LGTM 👍 
I made a suggestion regarding the conditions to make the workflow clearer.

2022-10-20 10:45 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
>  			}
as said on slack, I feel like the order of the checks does not reflect the order in which it happens in reality.

I would prefer something like this to show the different states/conditions in the order they appear:

1. not in autonomous mode
2. in autonomous mode && not playing
3. in autonomous mode && playing --> what happens in this case?

```cpp
if (is_not_autonomous_mode) {
	start = rtos::Kernel::Clock::now();

	if (start - stop > 1s) {
		raiseAutonomousActivityModeRequested();
	}

	return;
}

if (is_autonomous_mode && is_not_playing) {
	stop = rtos::Kernel::Clock::now();

	if (stop - start > 2s) {
		raiseAutonomousActivityModeExited();
	}

	return;
}

if (is_autonomous_mode && is_playing) {
	// do nothing
	return;
}
```

I personally don't really like the `else if` as I find it harder to read and to follow through the branching, but this case is simple enough to use it if you really want:

```cpp
if (is_not_autonomous_mode) {
	start = rtos::Kernel::Clock::now();

	if (start - stop > 1s) {
		raiseAutonomousActivityModeRequested();
	}
} else if (is_autonomous_mode && is_not_playing) {
	stop = rtos::Kernel::Clock::now();

	if (stop - start > 2s) {
		raiseAutonomousActivityModeExited();
	}
} else {
	// is_autonomous_mode && is_playing
	// do nothing
}
```

2022-10-20 12:09 UTC, YannLocatelli requested changes
- [ ] Validated on the robot

A case is not covered or all cases are not clearly specified.

Some question about tests

2022-10-20 12:09 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateIdle.cpp
> +}
Also, is `using namespace std::chrono;` important?

2022-10-20 12:09 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateAutonomousActivities.cpp
> +	activitykit.start(MagicCard::number_10);
```suggestion
	auto set_activitykit_is_playing = [this] {
		const std::unordered_map<MagicCard, interface::Activity *> activities {{MagicCard::number_10, &display_tag}};
		activitykit.registerActivities(activities);
		EXPECT_CALL(mock_videokit, displayImage).Times(1);
		activitykit.start(MagicCard::number_10);
	};

	set_activitykit_is_playing();
```

2022-10-20 12:09 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
>  			}
Does this still work if not using `else if`? Validation on robot will confirm this.

2022-10-21 13:04 UTC, YannLocatelli commented on libs/RobotKit/include/StateMachine.h
> +			, sm::state::autonomous_activities + event<sm::event::autonomous_activities_mode_exited>                                            = sm::state::idle
`autonomous_activities` state is available while connected in BLE

Transition from `autonomous_activities` state to `working` state was missing

2022-10-21 16:38 UTC, YannLocatelli reviewed
Some suggestions

Some code is not covered according to sonarcloud, but no clue on how to reach them considering preceding conditions

2022-10-21 16:38 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateWorking.cpp
> +	activitykit.start(MagicCard::number_10);
You can refactor this one as you did for `stateGameActivityStartedBackToMenu`

```suggestion
	auto set_activitykit_is_playing = [this] {
		const std::unordered_map<MagicCard, interface::Activity *> activities {{MagicCard::number_10, &display_tag}};
		activitykit.registerActivities(activities);
		EXPECT_CALL(mock_videokit, displayImage).Times(1);
		activitykit.start(MagicCard::number_10);
	};
	set_activitykit_is_playing();
```

2022-10-21 16:38 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateAutonomousActivities.cpp
> +	activitykit.start(MagicCard::number_10);
Since it's setup, I suggest the same lambda func above `set_activitykit_is_playing`

2022-10-21 16:38 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateWorking.cpp
> +}
According to sonarcloud, 1 condition is missing, I suppose `is_NOT_playing && is_NOT_autonomous_mode`

https://github.com/leka/LekaOS/blob/a587177bba74b36bc3f910352174369afe67bdc2/libs/RobotKit/include/RobotController.h#L335

```suggestion
}

// ! TODO: Refactor with composite SM & CoreTimer mock
TEST_F(RobotControllerTest, stateWorkingActivityStartedNotPlaying)
{
	rc.state_machine.set_current_states(lksm::state::working);

	auto maximal_delay_before_over = 1s;

	spy_kernel_addElapsedTimeToTickCount(maximal_delay_before_over);
	rc.onMagicCardAvailable(MagicCard::number_0);

	EXPECT_TRUE(rc.state_machine.is(lksm::state::working));
}
```

2022-10-21 16:38 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateAutonomousActivities.cpp
> +TEST_F(RobotControllerTest, stateGameActivityStartedBackToMenu)
According to sonarcloud, 1 condition is missing 

https://github.com/leka/LekaOS/blob/a587177bba74b36bc3f910352174369afe67bdc2/libs/RobotKit/include/RobotController.h#L328

I suppose

```suggestion
// ! TODO: Refactor with composite SM & CoreTimer mock
TEST_F(RobotControllerTest, stateGameActivityStartedBackToMenuDelayNotOver)
{
	auto maximal_delay_before_over = 1s;

	rc.state_machine.set_current_states(lksm::state::autonomous_activities);

	auto set_activitykit_is_playing = [this] {
		const std::unordered_map<MagicCard, interface::Activity *> activities {{MagicCard::number_10, &display_tag}};
		activitykit.registerActivities(activities);
		EXPECT_CALL(mock_videokit, displayImage).Times(1);
		activitykit.start(MagicCard::number_10);
	};
	set_activitykit_is_playing();

	EXPECT_CALL(mock_videokit, displayImage).Times(0);

	spy_kernel_addElapsedTimeToTickCount(maximal_delay_before_over);
	rc.onMagicCardAvailable(MagicCard::dice_roll);

	EXPECT_TRUE(rc.state_machine.is(lksm::state::autonomous_activities));
}

// ! TODO: Refactor with composite SM & CoreTimer mock
TEST_F(RobotControllerTest, stateGameActivityStartedBackToMenu)
```

2022-10-24 09:51 UTC, ladislas reviewed
LGTM 👍

2022-10-24 09:59 UTC, YannLocatelli approved these changes

2022-10-24 10:01 UTC, YannLocatelli commented
Linked to 

- #1058

2022-10-24 11:32 UTC, merged