:sparkles: (drivers): [CoreVideo] Suspend pwm back light when off
leka/LekaOS pull request #1168
Opened 2022-11-28 16:29 UTC by ladislas

2022-11-29 17:06 UTC, YannLocatelli requested changes
Thank you for your work~

Still a bug for functional test only and some other comments

2022-11-29 17:06 UTC, YannLocatelli commented on tests/functional/tests/deep_sleep_core_video/suite_core_video.cpp
> +					expect(status.test_check_ok);
I do not have explanation for now, investigating for now~

2022-11-29 17:10 UTC, YannLocatelli commented on tests/functional/tests/deep_sleep_core_video/suite_core_video.cpp
> +	};
There is a lot of initialization in this file, not sure it helps

2023-01-03 16:44 UTC, ladislas commented
replaced by #1173

2023-01-03 16:44 UTC, closed without merging