:children_crossing: (emergency stop): Add minimal delay to use emergency stop
leka/LekaOS pull request #1192
Opened 2022-12-08 14:15 UTC by HPezz

2022-12-08 14:28 UTC, ladislas reviewed
LGTM 👍

2022-12-08 14:28 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +		if (card == MagicCard::emergency_stop && rtos::Kernel::Clock::now() - init_timestamp > 10s) {
separate it in two checks as they are not relevant at the same time:

```suggestion
		if (rtos::Kernel::Clock::now() - init_timestamp < 10s) {
			return;
		}
		
		if (card == MagicCard::emergency_stop) {
```

2022-12-08 14:28 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	rtos::Kernel::Clock::time_point init_timestamp = rtos::Kernel::Clock::now();
can be made `const`

```suggestion
	const rtos::Kernel::Clock::time_point kSystemStartupTimestamp = rtos::Kernel::Clock::now();
```

2022-12-08 14:29 UTC, ladislas approved these changes

2022-12-12 09:36 UTC, ladislas approved these changes
LGMT 👍

2022-12-12 09:38 UTC, merged

2022-12-12 09:44 UTC, YannLocatelli requested changes
A question about a delay, and a suggestion to move the delay to be more accessible.

2022-12-12 09:44 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateIdle.cpp
> +	auto minimal_delay_over = 1001s;
Why this change from `ms` to `s` ?

If you want a delay over 11s, it is just `11s` or `11001ms`

2022-12-12 09:44 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
> +		if (card == MagicCard::emergency_stop && rtos::Kernel::Clock::now() - kSystemStartupTimestamp > 10s) {
You don't want a parameter as the startup duration to be drown in the code, I suggest to set at the start of the method or set in member variables.