hugo/feature/Change animation blinkOnCharge
leka/LekaOS pull request #1218
Opened 2022-12-15 17:04 UTC by HPezz

- :children_crossing: (MotionKit): Improve smart reinforcer performance
- :recycle: (MotionKit): Add timeout to rotate() function
- :recycle: (libs): Update Motionkit calls
- :children_crossing: (BlinkOnCharge): Improve animation
- :children_crossing: (BehaviorKit): Trigger back BlinkOnCharge after BleConnection

2022-12-15 23:30 UTC, ladislas requested changes
LGTM besides stage naming 👍

2022-12-15 23:30 UTC, ladislas commented on libs/LedKit/include/animations/BlinkOnCharge.h
> +	void stage2();
can you name them something meaningful as you only have 3 and they do specific things

2022-12-16 09:54 UTC, YannLocatelli requested changes
Adding a charge notion in bleConnection is not good, and I just noticed that tests mention a condition on state connection or not: charging

State machine is composite, in the ideology to differentiate connection and robot states. So there are kind of not related.

Moreover Behaviors should not be aware of the state.

--

I don't have solution yet, I need some time to think about it.

2022-12-16 09:54 UTC, YannLocatelli commented on libs/BehaviorKit/source/BehaviorKit.cpp
> +		blinkOnCharge();
This function (bleConnection) does not have notion of charge, only of video.

This workaround is fine but bring some confusion in BehaviorKit implementation.

2022-12-16 11:42 UTC, YannLocatelli requested changes
A typo + missing case

2022-12-16 11:42 UTC, YannLocatelli commented on libs/BehaviorKit/tests/BehaviorKit_test.cpp
> -	EXPECT_CALL(mock_ledkit, start(isSameAnimation(&led::animation::ble_connection))).Times(1);
Keep this one

2022-12-16 13:08 UTC, YannLocatelli approved these changes

2022-12-16 16:33 UTC, ladislas approved these changes

2022-12-16 16:48 UTC, merged