♻️ Use std::function instead of mbed::Callback
leka/LekaOS pull request #1255
Opened 2023-01-13 21:45 UTC by YannLocatelli

# Validations

- [x] BLE
- [ ] Battery - onChargeDidStart
- [ ] Battery - onChargeDidStop
- [x] RFID

2023-01-14 19:11 UTC, ladislas requested changes
thanks for this PR! good to see mbed::callback going away in a lot of places :)

I've added a few suggestions where I think that mbed::callback can be completely removed and replaced by simple lambdas.

2023-01-14 19:11 UTC, ladislas commented on drivers/CoreBattery/source/CoreBattery.cpp
> +	_charge_status_input.rise(mbed::Callback<void()> {[this] { _on_charge_did_start(); }});
is it not possible to do just that? Do we really need to go from std::function to lambda to mbed::callback?

```suggestion
	_charge_status_input.rise([this] { _on_charge_did_start(); });
```

2023-01-14 19:11 UTC, ladislas commented on drivers/CoreBattery/source/CoreBattery.cpp
> +	_charge_status_input.fall(mbed::Callback<void()> {[this] { _on_charge_did_stop(); }});
same as above if possible

```suggestion
	_charge_status_input.fall([this] { _on_charge_did_stop(); });
```

2023-01-14 19:11 UTC, ladislas commented on drivers/CoreBufferedSerial/source/CoreBufferedSerial.cpp
> +	_serial.sigio(mbed::Callback<void()> {[this] { _sigio_callback(); }});
as we do in `CoreRFIDReaderCR95HF` mbed::callback could be removed

```suggestion
	_serial.sigio([this] { _sigio_callback(); });
```

2023-01-14 19:11 UTC, ladislas commented on libs/BLEKit/source/BLEKit.cpp
> +	_event_queue.call(mbed::Callback {&context->ble, &BLE::processEvents});
also here, is mbed::Callback really necessary compared to a lambda?

2023-01-18 11:25 UTC, HPezz reviewed
Nice 👍 

- [x] Validated on robot

2023-01-18 17:48 UTC, ladislas approved these changes

2023-01-18 17:48 UTC, merged