✨ (Firmware) - Add Format Factory
leka/LekaOS pull request #1259
Opened 2023-01-16 17:20 UTC by YannLocatelli

2023-01-18 09:55 UTC, HPezz approved these changes
👍

2023-01-18 18:52 UTC, ladislas requested changes
cool new feature as well, but we'll need to discuss this in our daily as I'm not sure I can grasp all the tenants et aboutissants of this change :)

2023-01-18 18:52 UTC, ladislas commented on libs/FirmwareKit/include/FirmwareKit.h
> +	auto loadFactory() -> bool final;
```suggestion
	auto loadFactoryFirmware() -> bool final;
```

2023-01-18 18:52 UTC, ladislas commented on libs/FirmwareKit/source/FirmwareKit.cpp
> +	return loadUpdate(Version {.major = 1, .minor = 0, .revision = 0});
I'm not sure I understand what is happening here.

if you can load the factory image, you return true meaning that it's the one who is going to be installed, right?

but if you can't, why would you load an update instead?

2023-01-19 11:27 UTC, ladislas approved these changes
LGTM 👍 just two small suggestions

2023-01-19 11:27 UTC, ladislas commented on libs/FirmwareKit/source/FirmwareKit.cpp
> +	if (auto does_factory_file_exist = _file.open(_config.factory_path); does_factory_file_exist) {
```suggestion
	if (auto factory_firmware_exists = _file.open(_config.factory_path); factory_firmware_exists) {
```

2023-01-19 11:27 UTC, ladislas commented on libs/FirmwareKit/source/FirmwareKit.cpp
> +		{.major = 1, .minor = 0, .revision = 0});	// ? Backward compatibility, factory file does not exist
```suggestion
	// ! IMPORTANT: BACKWARD COMPATIBILITY
	// ? This path is kept to handle the case where the bootloader has 
	// ? been updated but not the SD card, in which case the factory 
	// ? firmware might not exist. If it's the case, we must load the 
	// ? previous factory firmware which was LekaOS-1.0.0.bin
	// ? This should only happen when a robot is sent back to be fixed 
	// ? and used internally, but never for products in the field as 
	// ? the bootloader cannot change.
	return loadFirmware(
		{.major = 1, .minor = 0, .revision = 0});	
```

2023-01-20 10:26 UTC, ladislas approved these changes
LGTM 👍

2023-01-20 11:18 UTC, merged