hugo/feature/Create CoreInterruptIn
leka/LekaOS pull request #1262
Opened 2023-01-19 14:29 UTC by HPezz

- :building_construction: (Interface): Add InterruptIn interface
- :sparkles: (CoreInterruptIn): Create leka CoreInterruptIn wrapper
- :white_check_mark: (CoreInterruptIn): Add CoreInterruptIn_test

2023-01-20 14:05 UTC, YannLocatelli commented on drivers/CoreInterruptIn/source/CoreInterruptIn.cpp
> +}
Regarding recent discovery, maybe should call the callback in event queue

```suggestion
void CoreInterruptIn::rise(std::function<void()> const &callback)
{
	_on_rise_callback = callback;
	_interrupt_in.rise(mbed::Callback<void()> {[this] { _event_queue.call( [this] { _on_rise_callback(); } ) }});
}

void CoreInterruptIn::fall(std::function<void()> const &callback)
{
	_on_fall_callback = callback;
	_interrupt_in.fall(mbed::Callback<void()> {[this] { _event_queue.call( [this] { _on_fall_callback(); } ) }});
}
```

2023-01-20 14:05 UTC, YannLocatelli commented on drivers/CoreInterruptIn/include/CoreInterruptIn.h
> +	explicit CoreInterruptIn(PinName pin) : _pin(pin) {};
Does this work?

```suggestion
	explicit CoreInterruptIn(PinName pin) : _interrupt_in(pin) {};
```

2023-01-21 07:36 UTC, ladislas requested changes
LGTM 👍 
except for the CoreEventQueue which must be removed

2023-01-21 07:36 UTC, ladislas commented on drivers/CoreInterruptIn/include/CoreInterruptIn.h
> +	mbed::InterruptIn _interrupt_in;
as there is only one pin:

```suggestion
	explicit CoreInterruptIn(PinName pin) : _pin(pin) { _event_queue.dispatch_forever(); };

	auto read() -> int final;

	void rise(std::function<void()> const &callback) final;
	void fall(std::function<void()> const &callback) final;

  private:
	CoreEventQueue _event_queue;
	mbed::InterruptIn _pin;
```

2023-01-21 07:36 UTC, ladislas commented on drivers/CoreInterruptIn/include/CoreInterruptIn.h
> +	CoreEventQueue _event_queue;
as explained on slack, this should be removed.

interrupts are very low level hardware primitive used to react **instantly** when they trigger.

event queues are used to differ execution of slow parts of code outside of ISR context.

the fact that we need to use an event queue after an interrupt is an implementation detail and should be handled by the developper.

CoreInterruptIn must be kept as low level and fast as possible.

2023-01-21 07:36 UTC, ladislas commented on include/interface/drivers/InterruptIn.h
> +	virtual void fall(std::function<void()> const &callback) = 0;
i would add an `on`

```suggestion
	virtual void onRise(std::function<void()> const &callback) = 0;
	virtual void onFall(std::function<void()> const &callback) = 0;
```

2023-01-23 14:16 UTC, ladislas approved these changes
LGTM 👍

2023-01-23 14:16 UTC, merged