Yann/test/rfid/deep sleep rfidkit functional tests
leka/LekaOS pull request #1385
Opened 2024-02-02 18:06 UTC by YannLocatelli

# Requirements

- [ ] #1366

2024-02-02 18:07 UTC, YannLocatelli commented
Missing card on robot of functional test

2024-07-10 15:05 UTC, ladislas requested changes
lGTM modulo le wording pour les tests rfid

2024-07-10 15:05 UTC, ladislas commented on tests/functional/tests/deep_sleep_rfid_kit/suite_rfid_kit.cpp
> +				then("I expect TO detect card") = [&cardDetected] { expect(cardDetected); };
```suggestion
				then("I expect card TO BE detected") = [&cardDetected] { expect(cardDetected); };
```

2024-07-10 15:05 UTC, ladislas commented on tests/functional/tests/deep_sleep_rfid_kit/suite_rfid_kit.cpp
> +				then("I expect TO NOT detect card") = [&cardDetected] { expect(not cardDetected); };
```suggestion
				then("I expect card TO NOT BE detected") = [&cardDetected] { expect(not cardDetected); };
```

2024-07-10 15:05 UTC, ladislas commented on tests/functional/tests/deep_sleep_rfid_kit/suite_rfid_kit.cpp
> +				then("I expect TO detect card") = [&cardDetected] { expect(cardDetected); };
same as above

2024-07-11 15:08 UTC, merged