:art: (functional): Move utils in tests namespace
leka/LekaOS pull request #1391
Opened 2024-02-06 09:28 UTC by YannLocatelli

2024-07-10 14:34 UTC, ladislas requested changes
proposition pour ne pas avoir à rajouter `tests::` partout en faisant une extension de `leka::utils`

si ça marche pas on gardera ta solution

2024-07-10 14:34 UTC, ladislas commented on tests/functional/include/tests/utils.h
> +namespace tests::utils {
est-ce qu'on peut pas plutôt faire une extension de `leka::utils`?

```suggestion
namespace leka::utils {
```

puis dans les tests tu fais `using namespace leka`

2024-07-10 15:17 UTC, YannLocatelli commented on tests/functional/include/tests/utils.h
> +namespace tests::utils {
On retombe sur l'erreur avec ce changement

<img width="891" alt="Screenshot 2024-07-10 at 17 12 25" src="https://github.com/leka/LekaOS/assets/45776332/c23befcc-73ed-46a3-bec7-78f4cb523faa">

2024-07-11 11:22 UTC, YannLocatelli commented
Closed in favor of #1447

2024-07-11 11:22 UTC, closed without merging