:sparkles: (drivers): DAC and DACTimer drivers
leka/LekaOS pull request #302
Opened 2021-08-02 15:49 UTC by SamHadjes

2021-08-05 21:46 UTC, ladislas requested changes
Premier passage pour des petites corrections, j'attaque en détails demain 👍

2021-08-06 08:46 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +class DacTimer
L'idée du DacTimer était basée sur le fait qu'on utilise un des deux Basic Timers de la carte qui sont spécifiquement prévus pour pouvoir être connectés au DAC en physique.

![image](https://user-images.githubusercontent.com/48731907/128483263-da5fda5d-3a43-4f31-a4ad-91f8f596b908.png)

Du coup, on pourrait la renommer STM32BasicTimer ou quelque chose du genre, ce qui nous permettrait de servir de base pour utiliser TIM6 ou TIM7 de cette façon.
Mais si on voulait la rendre plus générique pour n'importe quel timer, ça demanderait d'avoir une méthode `attachCallback()` ou quelque chose du genre, et ensuite de ne pas l'implémenter dans notre driver...

2021-08-06 09:15 UTC, SamHadjes commented on mbed_app.json
> +}
elle est automatiquement supprimée par clang-format au moment de sauvegarder le fichier

2021-08-06 09:50 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +	virtual void _mspDeInitCallback()	 = 0;
> `msp` ?

MCU Support Package
> les callbacks ils sont avant ou après le init/deinit?

C'est un peu étrange, mais en gros, pour certains calls du HAL, il faut avoir effectué quelques opérations en interne d'abord.
Quand on call  `HAL_TIM_Base_Init()`, la fonction effectue quelques opérations, puis appelle mspInit(), puis refait quelques opérations.
Donc le callback doit être défini avant d'appeler `HAL_TIM_Base_Init()` parce qu'il est exécuté au milieu.

2021-08-06 10:07 UTC, SamHadjes commented on include/interface/drivers/Dac.h
> +class Dac
On avait mis les minuscules pour suivre l'exemple de `PwmOut.h` au lieu de `PWMOut.h`
La convention est-elle ? :
- acronyme tout seul --> majuscules
- acronyme suivi de quelque chose --> minuscules sur la fin de l'acronyme

Dans ce cas là, est-ce qu'il faut qu'on renomme `CoreDACTimer` en `CoreDacTimer` ?

2021-08-06 10:40 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +	virtual auto getHandle() -> TIM_HandleTypeDef = 0;
En vérifiant notre code, le seul endroit où la méthode est utilisée, c'est dans les tests. On vérifie des valeurs de configuration avec.
On a pas encore validé les tests pour les commit, mais ça ressemble à ça :

```
TEST_F(CoreDACTimerTest, handleConfigurationInstance)
{
	auto handle = coredactimer.getHandle();

	ASSERT_EQ(handle.Instance, TIM6);
}
```

Du coup, soit on supprime la méthode vu qu'elle n'est pas très utile, mais on ne peut plus tester.
Sinon effectivement on peut la faire passer au niveau de CoreDACTimer, vu qu'elle n'est pas nécessaire dans un mock.

2021-08-06 10:49 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +  protected:
Je crois qu'on avait mis ça parce qu'on avait eu besoin qu'elles soient public pour les tests.
Comme ils ne viennent pas dans cette PR, on remet en private et ça sera fix dans l'autre sens si besoin est :)

2021-08-06 10:58 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +	virtual void deInitialize()					= 0;
`deInitialize` appelle `HAL_TIM_Base_DeInit` qui disable le timer et appelle `_mspDeInitCallback` qui disable la clock du timer en question.

Terminate correspond assez bien à cette fonction aussi, on avait gardé le nom de la fonction du HAL appelée.

2021-08-06 11:11 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +	virtual auto _calculatePeriod(uint32_t freq) -> uint32_t = 0;
Le problème, c'est que `calculatePeriod()` fait appel à une methode de `STM32Hal` et à des MACRO de la board pour connaitre là fréquence de la clock du timer (elle peut être config à 54MHz ou 108MHz).

Donc si on la met dans l'interface, on est obligés d'avoir des dépendances en plus, et je crois que c'est ce que tu voulais éviter.

2021-08-06 12:32 UTC, ladislas commented on mbed_app.json
> +}
par clang format je pense pas, par vscode oui possible. mais normalement avec le plugin editorconfig (https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) ça doit la rajouter "on save"
![image](https://user-images.githubusercontent.com/2206544/128510702-8d694160-e463-454d-a536-593224b0c863.png)

2021-08-06 12:44 UTC, ladislas commented on include/interface/drivers/DacTimer.h
> +class DacTimer
dans ce cas là, on fait `leka::interface::stm32::BasicTimer` avec un enum class ou static struct qui donne soit TIM6 soit TIM7 (vous utilisez lequel?)

2021-08-06 13:01 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +class DacTimer
> vous utilisez lequel?

On est sur TIM6 par défaut, mais je crois que rien n'empêche d'utiliser le 7.

2021-08-06 13:22 UTC, ladislas commented on include/interface/drivers/Dac.h
> +class Dac
Pwm c'est parce que mbed l'écrit comme ça. 

DAC, c'est toujours DAC.

pour le nom, j'ai l'impression que DACTimer est internal. dans ce cas pas besoin du Core, tu fais juste une class DACTimer qui est que pour le DAC

2021-08-06 13:53 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +class DacTimer
Résolu: 
l'interface est maintenant `leka::interface::stm32::BasicTimer`
dans `BasicTimer.h`

2021-08-06 16:08 UTC, SamHadjes commented on drivers/CoreAudio/include/internal/CoreDACTimer.h
> +class CoreDACTimer : public interface::stm32::BasicTimer
Est-ce que `CoreDACTimer` peut-être internal à `DAC`, et donc renommé en `DACTimer`?

2021-08-09 06:07 UTC, ladislas commented on drivers/CoreAudio/include/internal/CoreDACTimer.h
> +class CoreDACTimer : public interface::stm32::BasicTimer
oui carrément. il n'y a que le dac qui utilise DACTimer, donc internal suffit, pas besoin du Core

2021-08-09 09:07 UTC, SamHadjes commented on drivers/CoreAudio/source/CoreDAC.cpp
> +	_hal.HAL_DAC_Start_DMA(&_hdac, DAC_CHANNEL_1, (uint32_t *)pData, dataLength, DAC_ALIGN_12B_R);
static cast

2021-08-09 09:09 UTC, SamHadjes commented on drivers/CoreAudio/source/CoreDAC.cpp
> +{
mettre en plusieurs lignes

2021-08-09 09:12 UTC, SamHadjes commented on drivers/CoreAudio/source/CoreDAC.cpp
> +	__HAL_LINKDMA(&_hdac, DMA_Handle1, _hdma);
mettre dans le HAL

2021-08-09 14:02 UTC, SamHadjes commented on drivers/CoreAudio/source/CoreDAC.cpp
> +	__HAL_LINKDMA(&_hdac, DMA_Handle1, _hdma);
difficile à inclure dans el HAL parce que c'est une macro

2021-08-10 12:08 UTC, SamHadjes commented on include/interface/drivers/DacTimer.h
> +	virtual void _mspDeInitCallback()	 = 0;
L'interace a été supprimée.
Je vais modifier les noms des méthodes dans la classe

2022-01-24 15:30 UTC, closed without merging