:construction: (spikes): Add LogKit format spike
leka/LekaOS pull request #347
Opened 2021-09-28 09:45 UTC by ladislas

2021-12-16 16:21 UTC, YannLocatelli requested changes
- [x] Test Enable Debug ON
- [x] Test Enable Debug OFF
- [ ] Spike - BLE
- [x] Spike - File Manager
- [x] Spike - Flash memory
- [ ] Spike - LCD
- [x] Spike - LEDs
- [x] Spike - LogKit
- [x] Spike - Sensors Batteries
- [x] Spike - Sensors - Température
- [ ] Spike - Wifi

2021-12-16 21:09 UTC, YannLocatelli commented
Pour le BLE, en mettant en commentaire le LogKit dans le PrettyPrinter [[Link](https://github.com/leka/LekaOS/blob/develop/libs/PrettyPrinter/source/PrettyPrinter.cpp#L7)] et les autres logs du fichier ça fonctionne de nouveau.

Je ne sais pas ce qui entre en conflit mais ça vient de là.

2021-12-16 22:11 UTC, ladislas commented on libs/LogKit/tests/LogKit_test_log.cpp
> +	logger::init();
décrire comment ça?

2021-12-21 11:01 UTC, YannLocatelli commented on libs/LogKit/tests/LogKit_test_log.cpp
> +	logger::init();
Quelles sont les fonctions appelées dans` logger::init()`, est-ce que ce seront toujours celles-ci ou est-ce que ça n'a pas d'importance si on en appelle d'autres?

2021-12-24 12:55 UTC, YannLocatelli approved these changes
- [x] Test Enable Debug ON
- [x] Test Enable Debug OFF [LogKit, LCD, Wifi]
- [x] Spike - BLE
- [x] Spike - File Manager
- [x] Spike - Flash memory
- [x] Spike - LCD
- [x] Spike - LEDs
- [x] Spike - LogKit
- [x] Spike - Sensors Batteries
- [x] Spike - Sensors - Température
- [x] Spike - Wifi

2021-12-24 12:55 UTC, YannLocatelli commented on libs/LogKit/include/LogKit.h
> +namespace logger {
clang-tidy recommande

```cpp
namespace leka::logger {
```

2021-12-24 12:55 UTC, YannLocatelli commented on spikes/lk_log_kit/include/utils.h
> +// Copyright 2020 APF France handicap
```suggestion
// Copyright 2021 APF France handicap
```

2021-12-24 12:55 UTC, YannLocatelli commented on libs/LogKit/tests/LogKit_test_log.cpp
> +	logger::init();
> Pour le moment c’est celles-ci, si besoin dans le futur on en mettra d’autre mais de toute manière l’utilisateur peut pas le modifier, pas plus que pour une autre classe ou une autre fonction.

A mon sens, les tests sont là pour éviter toute modification malencontreuse du code (utilisateur ou non). Si demain je modifie cet `init` et que plus rien ne fonctionne, aucun test ne le signalera.

Comme tu sembles confiant en la matière je vais valider la PR.

Aussi je tiens à recommander, sur la base de nos précédentes discussions, de ne pas utiliser un terme générique comme `init` ni d'avoir des contraction pour être le plus explicite possible.

2021-12-29 08:24 UTC, merged