:sparkles: (drivers): Add CoreSPI
leka/LekaOS pull request #423
Opened 2022-01-19 11:35 UTC by HPezz

2022-01-19 15:42 UTC, ladislas requested changes
good first PR! 👍 

quelques trucs à faire:

- revoir les suggestions et les intérgrer
- supprimer le dossier CoreLED et toutes les références
- il y a un mocks/leka/SPI.h vide qui traine
- changer tous les 2021 en 2022

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreLED/CMakeLists.txt
> +
delete linebreak
```suggestion
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreLED/CMakeLists.txt
> +add_library(CoreLED STATIC)
ce fichier CoreLED il devrait pas être dans cette PR, ça serait bien de les supprimer pour ne les ajouter que dans la PR CoreLED

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreLED/CMakeLists.txt
> +add_library(CoreLED STATIC)
pareil pour CoreLED.h et .cpp, en gros tous le dossier CoreLED

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/CMakeLists.txt
> +target_link_libraries(CoreSPI mbed-os)
```suggestion
target_link_libraries(CoreSPI
	mbed-os
)
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/include/CoreSPI.h
> +// Copyright 2021 APF France handicap
pour @YannLocatelli  ;)

```suggestion
// Copyright 2022 APF France handicap
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/include/CoreSPI.h
> +class CoreSPI : public interface::SPI
je vois pas de fonction `read`?

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/include/CoreSPI.h
> +	auto write(const uint8_t *tx_buffer, int tx_length, uint8_t *rx_buffer, int rx_length) -> int override;
même si `size_t == int`, ça rend l'interface plus clair de l'utiliser car on voit dans le nom du type qu'on attend une taille.

```suggestion
	auto write(const uint8_t *tx_buffer, size_t tx_length, uint8_t *rx_buffer, size_t rx_length) -> int override;
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/include/CoreSPI.h
> +	void unlock();
```suggestion
	void lock();
	void unlock();
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/include/CoreSPI.h
> +
grouper les write
```suggestion
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/source/CoreSPI.cpp
> +	return _spi.write(reinterpret_cast<const char *>(tx_buffer), tx_length, reinterpret_cast<char *>(rx_buffer),
rajouter le commentaire suivant:

```suggestion
	// ? NOLINTNEXTLINE - allow reinterpret_cast as there are no alternatives
	return _spi.write(reinterpret_cast<const char *>(tx_buffer), tx_length, reinterpret_cast<char *>(rx_buffer),
```

2022-01-19 15:42 UTC, ladislas commented on include/interface/drivers/SPI.h
> +class SPI
je ne vois pas de `read`.

2022-01-19 15:42 UTC, ladislas commented on include/interface/drivers/SPI.h
> +	virtual auto write(const uint8_t *tx_buffer, int tx_length, uint8_t *rx_buffer, int rx_length) -> int = 0;
```suggestion
	virtual auto write(int value) -> int = 0;
	virtual auto write(const uint8_t *tx_buffer, size_t tx_length, uint8_t *rx_buffer, size_t rx_length) -> int = 0;
```

2022-01-19 15:42 UTC, ladislas commented on tests/unit/stubs/stubs/mbed/source/SPI.cpp
> +	return 0;
la fonction write retourne le nombre de caractère écrits, ça serait bien qu'on fasse pareil icil.

2022-01-19 15:42 UTC, ladislas commented on tests/unit/stubs/stubs/mbed/source/SPI.cpp
> +	leka::spy_spi_int_value = value;
la fonction write retourne le nombre de caractère écrits, ça serait bien qu'on fasse pareil icil.

2022-01-19 15:42 UTC, ladislas commented on tests/unit/stubs/stubs/mbed/source/SPI.cpp
> +}
sauter une ligne
```suggestion

}
```

2022-01-19 15:42 UTC, ladislas commented on include/interface/drivers/SPI.h
> +#include <stdint.h>
c'est mieux d'utiliser les headers C++

```suggestion
#include <cstdint>
```

2022-01-19 15:42 UTC, ladislas commented on include/interface/drivers/SPI.h
> +// Copyright 2021 APF France handicap
```suggestion
// Copyright 2022 APF France handicap
```

2022-01-19 15:42 UTC, ladislas commented on tests/unit/stubs/stubs/mbed/SPI.h
> +// Copyright 2021 APF France handicap
```suggestion
// Copyright 2022 APF France handicap
```

2022-01-19 15:42 UTC, ladislas commented on tests/unit/stubs/stubs/mbed/source/SPI.cpp
> +// Copyright 2021 APF France handicap
```suggestion
// Copyright 2022 APF France handicap
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/CMakeLists.txt
> +# Copyright 2021 APF France handicap
```suggestion
# Copyright 2022 APF France handicap
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/source/CoreSPI.cpp
> +// Copyright 2021 APF France handicap
```suggestion
// Copyright 2022 APF France handicap
```

2022-01-19 15:42 UTC, ladislas commented on drivers/CoreSPI/tests/CoreSPI_test.cpp
> +// Copyright 2021 APF France handicap
```suggestion
// Copyright 2022 APF France handicap
```

2022-01-23 14:06 UTC, ladislas approved these changes
LGTM 👍

2022-01-24 10:48 UTC, YannLocatelli approved these changes
Modulo la question à propos de `override` et la suggestion d'initialisation dans les tests, c'est tout bon pour moi 👍

2022-01-24 10:48 UTC, YannLocatelli commented on drivers/CoreSPI/include/CoreSPI.h
> +	auto write(std::span<uint8_t> data) -> size_t override;
Il y a une raison pour laquelle c'est `override` et pas `final` ?

2022-01-24 10:48 UTC, YannLocatelli commented on drivers/CoreSPI/tests/CoreSPI_test.cpp
> +	expected_written_values = {0x01};
Je recommande plutôt de le créer ici plutôt que dans la classe un peu plus haut

```suggestion
	auto expected_written_values = std::vector<uint8_t> {0x01};
```

Ca prend pas plus de place et c'est plus lisible d'une part quand on lit l'entête des classe et pour identifier rapidement quel type on envoie en test

2022-01-24 10:48 UTC, YannLocatelli commented on drivers/CoreSPI/tests/CoreSPI_test.cpp
> +	std::vector<uint8_t> expected_written_values {};
```suggestion
```

2022-01-24 11:36 UTC, merged