:sparkles: (spikes): Add lk_led_
leka/LekaOS pull request #473
Opened 2022-01-28 16:38 UTC by HPezz

Create a spike lk_led tthat does not use FastLED but CoreLED instead.

2022-01-30 22:12 UTC, ladislas requested changes
premier passage! 👍

2022-01-30 22:12 UTC, ladislas commented on spikes/lk_led_/main.cpp
> +const std::array<RGB, 6> COLORS = {
```suggestion
constexpr std::array<RGB, 6> COLORS = {
```

2022-01-30 22:12 UTC, ladislas commented on spikes/lk_led_/main.cpp
> +void ChangeColor(CoreLED coreled, uint8_t index)
c'est mieux de passer les objects comme ça par référence, ça évite une copie.

```suggestion
void changeColor(CoreLED& coreled, uint8_t index)
```

2022-01-30 22:12 UTC, ladislas commented on spikes/lk_led_/main.cpp
> +	CoreLED ear(corespi_ear, NUM_EAR_LEDS);
c'est mieux de les sortir du `main`

comme ça ils sont instanciés par le compilateur et pas par le run time (en théorie), ça permet en théorie d'être plus "static"

2022-01-30 22:12 UTC, ladislas commented on spikes/lk_led_/main.cpp
> +		ChangeColor(ear, index);
c'est moins important parce que c'est un spike, mais ton index comme ça il pourrait être une variable static de changeColor.
généralement on aime pas trop les variables static mais là ça s'y prête pas mal

2022-01-31 10:03 UTC, YannLocatelli commented on spikes/CMakeLists.txt
> +add_subdirectory(${SPIKES_DIR}/lk_coreled)
Je me demande si tu n'as pas meilleur temps d'utiliser directement le spike lk_led. Je me dis que les spikes sont juste une démo d'une fonctionnalité d'une robot et qu'en ayant plusieurs spikes de led on ne sache plus avec le temps lequel est le plus mis à jour des deux.

Si on ne le retire pas tout de suite, à quel moment va-t-on le retirer?

2022-01-31 10:09 UTC, ladislas commented on spikes/CMakeLists.txt
> +add_subdirectory(${SPIKES_DIR}/lk_coreled)
dans ma tête:

- on garde lk_led pour le moment, le temps qu'on développe le reste, il y a des choses intéressantes dedans
- on ajoute lk_coreled
- on ajout lk_ledkit
- une fois que lk_ledkit remplace lk_led, on supprime le dernier et tout le code qui n'est utilisé que par lui

2022-01-31 10:11 UTC, HPezz commented on spikes/CMakeLists.txt
> +add_subdirectory(${SPIKES_DIR}/lk_coreled)
Si vous avez plus besoin d'une démo avec FastLED, je change en effet mon lk_coreled en lk_led. En tous cas vous utilisez jamais le préfixe "core" pou rvos spikes donc si vous voulez garder la démo fastled, je suis d'avis de changer lk_led en lk_fastled et de changer lk_coreled en lk_led

2022-01-31 14:09 UTC, merged