✨ (sm): Add Sleep state
leka/LekaOS pull request #475
Opened 2022-01-31 15:57 UTC by YannLocatelli

2022-02-01 15:39 UTC, ladislas requested changes
ça me semble très bien! 👍 

pour moi il faut préciser à quoi sert chaque timeout. on en a qu'un là, mais très vite on a va en avoir plusieurs.

va aussi se poser la question de l'injection de dépendance au niveau du constructeur de RC : peut être que les timeout peuvent être des variable membres pour ne pas en avoir 10 à passer au RC.

va se poser la question des tests, mais en soit on ne veut pas tester que le timeout marche ou est appelé, mais que l'état change ou que l'action a bien lieu. donc a priori ça ne sera pas très grave et un stub pourra faire l'affaire.

2022-02-01 15:39 UTC, ladislas commented on libs/RobotKit/include/interface/RobotController.h
> +	virtual void stopTimeout()	= 0;
je pense qu'il faut être beaucoup plus précis concernant les noms des timeouts parce qu'on va en avoir plusieurs pour différentes choses.

```suggestion
	virtual void startGoToSleepTimeout() = 0;
	virtual void stopGoToSleepTimeout()	= 0;
```

2022-02-01 15:39 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	};
ici aussi, il faut que les timeout soient à quelque chose de spécifique; j'ai volontairement écrit `goToSleep` pour que ce soit facile à chercher avec cmd+F

```suggestion
	struct start_goToSleep_timeout {
		auto operator()(irc &rc) const { rc.startTimeout(); }
	};

	struct stop_goToSleep_timeout {
		auto operator()(irc &rc) const { rc.stopTimeout(); }
	};
```

2022-02-01 15:39 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	inline auto sleep	 = boost::sml::state<class sleep>;
puisqu'on parle de `state`, ça sera plutôt `sleeping`, comme `charging`

2022-02-02 08:02 UTC, YannLocatelli commented on libs/RobotKit/include/StateMachine.h
> +	};
En terme de style `snake_case` ça ne colle pas trop, c'est pas trop grave?

2022-02-02 14:52 UTC, ladislas approved these changes
tout est bon pour moi en terme de contenu, j'ai rajouté quelques suggestions sur les renames afin de remplacer tous les `timeout` seuls.

concernant le nom, je reviens un peu sur ma première review, j'étais pas très satisfait du "go to sleep", j'ai donc regardé dans la littérature et autres outils comment ils appelaient ce genre de chose :

- MS utilise [`Sleep unattended idle timeout`](https://docs.microsoft.com/en-us/windows-hardware/customize/power-settings/sleep-settings-sleep-unattended-idle-timeout) qui est une sur spécification du `idle` et équivalent donc à `sleep timeout` 
- Unity utilise [`SleepTimeout`](https://docs.unity3d.com/ScriptReference/SleepTimeout.html)

pour rester dans la même veine, on peut donc utiliser la même chose. j'ai fait les suggestions dans ce sens.

2022-02-02 14:52 UTC, ladislas commented on app/os/main.cpp
> +auto rc = RobotController {timeout, battery};
remplacer `timeout` par `sleep_timeout`

2022-02-02 14:52 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	interface::Timeout &_timeout;
```suggestion
	std::chrono::seconds _sleep_timeout_duration = std::chrono::seconds(10);
	interface::Timeout &_sleep_timeout;
```

2022-02-02 14:52 UTC, ladislas commented on libs/RobotKit/tests/RobotController_test.cpp
> +	mock::Timeout timeout {};
```suggestion
	mock::Timeout sleep_timeout {};
```

2022-02-02 14:52 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	struct timeout {
```suggestion
	struct sleep_timeout_did_end {
```

on trouve aussi `expire` plutôt que `end` dans la literature

2022-02-02 14:52 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	};
après réflexion, je reviens un peu sur ce que j'avais dit, cf mon commentaire de review.

```suggestion
	struct start_sleep_timeout {
		auto operator()(irc &rc) const { rc.startGoToSleepTimeout(); }
	};

	struct stop_sleep_timeout {
		auto operator()(irc &rc) const { rc.stopGoToSleepTimeout(); }
	};
```

2022-02-02 14:52 UTC, ladislas commented on libs/RobotKit/include/interface/RobotController.h
> +	virtual void stopGoToSleepTimeout()	 = 0;
```suggestion
	virtual void startSleepTimeout() = 0;
	virtual void stopSleepTimeout()	 = 0;
```

2022-02-02 16:13 UTC, merged