hugo/feature/Add color attribute for each led
leka/LekaOS pull request #477
Opened 2022-02-01 14:39 UTC by HPezz

- :pencil2: (drivers): Fix end frame to {0x00, 0x00, 0X00, 0x00}
- :art: (coreled): Create a CoreLED template
- :art: (coreled): Overload setColor() function

2022-02-01 16:30 UTC, ladislas requested changes
Premier passage! j'ai besoin de voir le code utilisé dans le spike pour me rendre compte de ce que ça donne.

ça te permettra à toi aussi de te rendre compte de l'API, est-ce que ça semble naturelle ou pas du tout.

2022-02-01 16:30 UTC, ladislas commented on drivers/CoreLED/include/CoreLED.h
> +	explicit CoreLED(interface::SPI &spi) : _spi {spi} { setAllBlackArray(); };
```suggestion
	explicit CoreLED(interface::SPI &spi) : _spi {spi} { 
		std::fill(_color.begin(), _color.end(), RGB::black);
	};
```

2022-02-01 16:59 UTC, HPezz commented on drivers/CoreLED/include/CoreLED.h
> +	std::array<RGB, NumberOfLeds> _all_black;
_all_black est là pour la fonction hideColor(). Comme précedemment, on veut conserver la donnée de couleur antérieur, on ne doit donc pas passer par setColor et passer un array full noir à sendAndDisplay. Je peux l'initialiser proprement avec std::fill cependant

2022-02-04 14:42 UTC, YannLocatelli approved these changes

2022-02-04 14:42 UTC, YannLocatelli commented on drivers/CoreLED/include/CoreLED.h
> +		_is_color_shown = false;
Pourquoi ne pas avoir fait
```suggestion	
		setColor(RGB::black);
		showColor();
```
C'est à propos des termes utilisés?

2022-02-04 14:42 UTC, YannLocatelli commented on drivers/CoreLED/tests/CoreLED_test_status.cpp
> +
Il manque un cas de figure:
```suggestion

TEST_F(CoreLedStatusTest, isOffIfShowAtInstanciationIsSetToNotBlack)
{
	leds.showColor();
	leds.setColor(RGB::pure_blue);
	EXPECT_FALSE(leds.isOn());
}

```

2022-02-04 14:42 UTC, YannLocatelli commented on drivers/CoreLED/tests/CoreLED_test_status.cpp
> +
Je me suis amusé à relever les différents cas de figure suivant la dernière consigne avant le EXPECT de `leds.isOn()`:

- Hide → `FALSE`
- Show, before set was
    - Missing → `FALSE`
    - Black → `FALSE`
    - Colored (black excluded) → `TRUE`
- Set → Same result as last Show
    - Missing Show → `FALSE`

2022-02-04 14:47 UTC, ladislas commented on drivers/CoreLED/include/CoreLED.h
> +		_is_color_shown = false;
parce que setColor il set la color donc on perd l'ancienne. là on affiche juste du noir, on peut ensuite la showColor pour la remontrer

2022-02-04 14:59 UTC, ladislas commented on drivers/CoreLED/tests/CoreLED_test_status.cpp
> +
si le cas est déjà là:

```
TEST_F(CoreLedStatusTest, isOffIfColorIsSetToNotBlack)
{
	leds.setColor(RGB::pure_blue);
	EXPECT_FALSE(leds.isOn());
}
```

le showColor sert à rien parce qu'il show la couleur par défault qui est black, ce qui est lui même testé ici 👍 

```
TEST_F(CoreLedStatusTest, isOffIfShowAtInstanciation)
{
	leds.showColor();
	EXPECT_FALSE(leds.isOn());
}
```

2022-02-07 13:44 UTC, merged