✨ (ble): Add CoreGattServerEventHandler
leka/LekaOS pull request #490
Opened 2022-02-09 11:04 UTC by YannLocatelli

Need #486 #489

2022-02-16 13:52 UTC, ladislas requested changes
reviewed! 👍  j'ai été un peu extensif, j'espère que c'est compréhensible :)

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +};
ici j'ai du mal à suivre et à comprendre à quoi tout sert:

- je sortirai bien les const pour les mettre dans un namespace `default` par exemple
- est-ce qu'on a besoin de tout ?
- est-ce qu'on peut séparer les tests en plusieurs fichiers qui testent des trucs plus spécifiques afin de réduire la complexité ?
- séparer les trucs nécessaires au setup mais qu'on teste pas, des trucs qu'on teste réellement

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	std::array<interface::BLEService *, _services_count> _services {&mock_service};
```suggestion
	uint8_t _characteristic_value {42};
	ReadOnlyGattCharacteristic<uint8_t> _characteristic {0x1234, &_characteristic_value};
	
	static const uint8_t _characteristics_count {1};
	std::array<GattCharacteristic *, _characteristics_count> _characteristics {&_writable_characteristic};
	
	const UUID _uuid {0x0001};
	mock::BLEService mock_service = mock::BLEService(_uuid, _characteristics, std::size(_characteristics);
	// ici je serai plutôt fan d'avoir:
	mock::BLEService mock_service = mock::BLEService({.uuid = 0x0001, .characteristics = _characteristics};
	// avec le size qui est déduit du array qu'on passe, voir commentaire tout en haut
		
	static const uint8_t _services_count {1};
	std::array<interface::BLEService *, _services_count> _services {&mock_service};
```

2022-02-16 13:52 UTC, ladislas commented on include/interface/drivers/BLEService.h
> +			: GattService(uuid, characteristics.data(), characteristics_count) {};
à minima 

```suggestion
		BLEService(const UUID &uuid, std::span<GattCharacteristic *> characteristics)
			: GattService(uuid, characteristics.data(), std::size(characteristics) {};
```

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	EXPECT_CALL(mock_service, updateData(compareUpdateServiceFunction(impostor_function))).Times(0);
ici tu testes avec `_characteristics_count` qui vaut `1` mais on sait pas si ça marche pour plus que `1` et que ça fait rien pour `0`

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	std::function<void()> impostor_function;
`dummy` et `impostor` c'est très proche en anglais, pour éviter la confusion dans l'usage, j'utiliserais des termes plus explicites par exemple:

- `function_called`
- `function_NOT_called`

comme ça on voit tout de suite qui fait quoi.

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	EXPECT_CALL(mock_service_2, updateData).Times(serivce_2_characteristics_count);
ici tu testes ce que je demandais plus haut mais à l'intérieur d'un test qui teste autre chose.

c'est peut être là que c'est intéressant de faire plusieurs fichiers pour tester:

- updateData et tous les cas d'usage
- getCharacteristicsCounts et tous les cas d'usages
- ondatawritten
- etc.

c'est pas grave d'avoir plein de fichiers ça rend les tests plus clair sur ce qu'ils testent réellement.

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +		mock::BLEService(uuid, service_2_characteristic_table, serivce_2_characteristics_count);
c'est très dur à lire et à suivre.

il faut mettre un peu plus d'`auto` et `std::to_array` et raccourcir le nom des variables.

```suggestion
	ReadOnlyGattCharacteristic<uint8_t> charac {0x1234, 0};
	auto s1_charac_table = std::to_array<GattCharacteristic *>({&charac}); // ? One characteristic
	auto s2_charac_table = std::to_array<GattCharacteristic *>({&charac, &charac}); // ? Two characteristics
	
	const UUID s1_uuid {0x0001};
	auto s1 = mock::BLEService(s1_uuid, s1_charac_table, std::size(s1_charac_table);
	const UUID s2_uuid {0x0002};
	auto s1 = mock::BLEService(s2_uuid, s2_charac_table, std::size(s2_charac_table);
```

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	GattWriteCallbackParams impostor_params;
même commentaire sur dummy/impostor, remplacer par `used` et `NOT_used`

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	ReadOnlyGattCharacteristic<uint8_t> _writable_characteristic {0x1234, &_characteristic_value};
tu l'appelles writable alors qu'elle est read only.

```suggestion
	ReadOnlyGattCharacteristic<uint8_t> _characteristic {0x1234, &_characteristic_value};
```

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	CoreGattServerEventHandler core_gatt_server_event_handler {};
```suggestion
	CoreGattServerEventHandler gatt_event_handler {};
```

2022-02-16 13:52 UTC, ladislas commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	MockFunction<updateServiceFunction> mock_server_write_func;
même point avec le naming.

2022-02-16 13:52 UTC, ladislas commented on include/interface/drivers/BLEService.h
> +	std::function<void(GattAttribute::Handle_t characteristic_updated, const uint8_t *data, uint16_t n_data_bytes)>;
et elle peut pas prendre un span plutôt qu'un * et un size?

2022-02-21 17:34 UTC, YannLocatelli commented on include/interface/drivers/BLEService.h
> +	std::function<void(GattAttribute::Handle_t characteristic_updated, const uint8_t *data, uint16_t n_data_bytes)>;
C'est déplacé

--

L'idée du span est intéressant mais il y a un bémol dans l'usage: parfois `uint8_t *data` pointe vers une variable de type `uint8_t` ou `bool`, donc pas nécessairement un type array

2022-02-21 17:34 UTC, YannLocatelli commented on include/interface/drivers/BLEService.h
> +		virtual auto getCharacteristic(uint8_t index) -> GattCharacteristic * { return getCharacteristic(index); };
Fixed

2022-02-21 17:34 UTC, YannLocatelli commented on include/interface/drivers/BLEService.h
> +			: GattService(uuid, characteristics.data(), characteristics_count) {};
Le `characteristics_count` a été retiré

2022-02-21 17:34 UTC, YannLocatelli commented on include/interface/drivers/BLEService.h
> +	class BLEService : public GattService
On est sur une interface. Comme expliqué à l'oral, on retrouvera plus tard `BLEService` qui servira pour les différents services à avoir les "bonnes fonctions"

2022-02-21 17:34 UTC, YannLocatelli commented on libs/BLEKit/include/CoreGattServerEventHandler.h
> +#include "interface/drivers/BLEService.h"
C'est déplacé

2022-02-21 17:34 UTC, YannLocatelli commented on libs/BLEKit/include/CoreGattServerEventHandler.h
> +	updateServiceFunction update_server_data {};
Ca a été retiré

2022-02-21 17:34 UTC, YannLocatelli commented on libs/BLEKit/source/CoreGattServerEventHandler.cpp
> +	}
Il y a eut un essai d'implémentation. Je ne suis pas sûr que ça apporte tant en lisibilité

2022-02-21 17:34 UTC, YannLocatelli commented on libs/BLEKit/source/CoreGattServerEventHandler.cpp
> +	}
Cette partie n'existe plus~

2022-02-21 17:35 UTC, YannLocatelli commented on libs/BLEKit/include/CoreGattServerEventHandler.h
> +	void registerServerWrite(updateServiceFunction const &function);
Ca a été retiré

2022-02-21 17:35 UTC, YannLocatelli commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	std::function<void()> impostor_function;
C'est remplacé

2022-02-21 17:35 UTC, YannLocatelli commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	GattWriteCallbackParams impostor_params;
C'est remplacé

2022-02-21 17:35 UTC, YannLocatelli commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	ReadOnlyGattCharacteristic<uint8_t> _writable_characteristic {0x1234, &_characteristic_value};
C'est corrigé

2022-02-21 17:35 UTC, YannLocatelli commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	CoreGattServerEventHandler core_gatt_server_event_handler {};
Done

2022-02-21 17:35 UTC, YannLocatelli commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	MockFunction<updateServiceFunction> mock_server_write_func;
Ca a été retiré

2022-02-22 16:37 UTC, ladislas commented on include/interface/drivers/BLEService.h
> +	std::function<void(GattAttribute::Handle_t characteristic_updated, const uint8_t *data, uint16_t n_data_bytes)>;
c'est pas très grave si c'est pas un array, si c'est juste une variable, tu peux faire passer `std::span{&i, 1}`

exemple: https://gcc.godbolt.org/z/nhPY7jKj7

2022-02-22 18:23 UTC, YannLocatelli commented on libs/BLEKit/include/internal/BLEService.h
> +namespace leka::interface {
Ah oui, c'est le fait d'avoir retiré les virtual qui fait qu'on a perdu le caractère de `interface`

Ce qui me gène, c'est que c'est un modèle et qu'il ne devrait pas donner l'idée qu'il puisse être utilisé autre qu'en tant que modèle. C'est aussi dans ce sens que va le `internal`...

Mais si on regarde dans le futur avec les dernières suggestions, dans la PR #485, on est amené à instancié un array avec du `interface::BLEService *`

2022-02-22 18:23 UTC, YannLocatelli commented on libs/BLEKit/include/internal/BLEService.h
> +	virtual void updateData()														= 0;
En relisant, c'est celui dans l'event handler qu'on ne peut pas le changer.

Ici comme le Service a été dissocié de l'event handler, on peut aujourd'hui lui donner le nom qu'on souhaite

---

Je vais me répéter mais la PR #485 permet de voir ce à quoi va ressembler un système qui utilise le server et des (un) services

Et actuellement il fait que du "setup" et n'est pas utilisé "on run": définir l'event handler pour le BLE, définir quels services vont être utilisés, définir comment écrire sur le serveur

2022-02-22 20:44 UTC, YannLocatelli commented on libs/BLEKit/tests/CoreGattServerEventHandler_test.cpp
> +	EXPECT_CALL(mock_service_2, updateData).Times(serivce_2_characteristics_count);
Il n'y a plus qu'une seule fonction testée: `onDataReceived`

2022-02-22 20:48 UTC, YannLocatelli commented on include/interface/drivers/BLEService.h
> +	class BLEService : public GattService
Discussion continué ici: https://github.com/leka/LekaOS/pull/490#discussion_r812236577

2022-02-24 23:19 UTC, closed without merging