🚚  (web): Move WebKit from FileReception spike to libs + add tests
leka/LekaOS pull request #491
Opened 2022-02-09 16:30 UTC by YannLocatelli

2022-02-16 16:42 UTC, ladislas requested changes
premier passage! c'est très intéressant 👍  à discuter demain :)

2022-02-16 16:42 UTC, ladislas commented on libs/WebKit/source/WebKit.cpp
> +	if (auto file_is_open = _file_handler.open(certificate_path, "r"); file_is_open) {
```suggestion
	if (auto is_open = _file_handler.open(certificate_path, "r"); is_open) {
```

2022-02-16 16:42 UTC, ladislas commented on libs/WebKit/source/WebKit.cpp
> +void WebKit::getRedirectionURL(WebResponse const &response)
```suggestion
void WebKit::getRedirectionUrl(WebResponse const &response)
```

2022-02-16 16:42 UTC, ladislas commented on libs/WebKit/source/WebKit.cpp
>  	auto containLocationField = [](const std::string *header_field) { return *header_field == "Location"; };
```suggestion
	auto containsLocationField = [](const std::string *field) { return *field == "Location"; };
```

2022-02-16 16:42 UTC, ladislas commented on libs/WebKit/include/WebKit.h
> +	void getRedirectionURL(WebResponse const &response);
```suggestion
	[[nodiscard]] auto responseHasRedirectionUrl(WebResponse const &response) const -> bool;
	void getRedirectionUrl(WebResponse const &response);
```

2022-02-16 16:42 UTC, ladislas commented on libs/WebKit/include/WebKit.h
> +	void getRedirectionURL(WebResponse const &response);
et est-ce qu'on les mettrait pas dans la struct `WebResponse` comme méthodes?

2022-02-16 16:42 UTC, ladislas commented on libs/WebKit/tests/WebKit_test.cpp
> +// Leka - LekaOS
je suis pas encore passé en détails ici, mais est-ce qu'on pourrait découper en plusieurs fichiers? certs, download, etc.

2022-02-22 22:26 UTC, YannLocatelli commented on drivers/CoreWifi/include/WebAccess.h
> +	CoreESP8266 wifi_module {WIFI_USART_TX, WIFI_USART_RX, false, WIFI_USART_RTS, WIFI_USART_CTS, WIFI_RESET};
`CoreESP8266` est basé sur l'interface donné par ESP et n'intègre pas de `enable`
C'est pour ça que `CoreWifi` a été ajouté pour associer les 2

2022-02-22 22:26 UTC, YannLocatelli commented on drivers/CoreWifi/source/WebAccess.cpp
> +auto WebAccess::connect(const char *ssid, const char *pass) -> bool
`WebAccess` hérite de nouvellement `Network`.

En plus d'avoir une multitude de Network qui peuvent porter à confusion (`interface::Network` et `CoreWifi::Network`), l'interface devrait dépendre d'une struct spécifique à CoreWifi

2022-02-22 22:26 UTC, YannLocatelli commented on drivers/CoreWifi/source/WebAccess.cpp
> +	if (auto *mbed_http_response = request->send(); mbed_http_response == nullptr) {
Ca peut prêter à confusion avec `_response`

2022-02-22 22:26 UTC, YannLocatelli commented on drivers/CoreWifi/source/WebAccess.cpp
> +							const std::function<void(const char *at, uint32_t length)> &body_callback) -> WebResponse &
`body_callback` sert à "gérer" la réponse reçue, ici elle est écrite dans le fichier

2022-02-22 22:26 UTC, YannLocatelli commented on drivers/CoreWifi/source/WebAccess.cpp
> +	request = make_unique<HttpsRequest>(&corewifi, ssl_ca_pem, HTTP_GET, url, casted_body_callback);
La requête est redéfinie à chaque fois, et la réponse de la requête est contenu dans `request`, d'où l'utilisation d'un pointeur

2022-02-22 22:26 UTC, YannLocatelli commented on drivers/CoreWifi/source/WebAccess.cpp
> +		response.headers_values = std::vector<std::string *> {};
Je sais, c'est la méthode de mbed_http

2022-02-22 22:27 UTC, YannLocatelli commented on include/interface/drivers/WebAccess.h
> +};
C'est pour faciliter l'emmêlement des tests qui est insupportable autrement. Si tu as une alternative, je suis preneur

2022-02-22 22:27 UTC, YannLocatelli commented on libs/WebKit/source/WebKit.cpp
> +			break;
Un cas d'usage qui n'était pas bien pris en compte:

Si on se réfère au `if` un peu plus haut, c'est dans le cas où le fichier où est sauvegardé le firmware ne s'ouvre pas pour une raison ou une autre

2022-02-22 22:28 UTC, YannLocatelli commented on libs/WebKit/tests/WebKit_test.cpp
> +// Leka - LekaOS
C'est découpé

2022-03-10 10:29 UTC, merged