✨ (video): Play video
leka/LekaOS pull request #703
Opened 2022-04-20 17:03 UTC by YannLocatelli

2022-04-20 21:21 UTC, ladislas approved these changes
LGTM 👍 

j'ai pas la compétence de dire si tout va marcher, mais niveau code, rien à redire :)

2022-04-21 09:39 UTC, HPezz requested changes

2022-04-21 09:39 UTC, HPezz commented on drivers/CoreVideo/source/CoreVideo.cpp
> +		frame_index = _corejpeg.findSOIMarker(file, frame_index + frame_size + 4);
Si le 4 importe pas ou on ne sait pas ce que c'est, autant l'enlever

```suggestion
		frame_index = _corejpeg.findSOIMarker(file, frame_index + frame_size);
```

2022-04-21 09:42 UTC, YannLocatelli commented on drivers/CoreVideo/source/CoreVideo.cpp
> +		frame_index = _corejpeg.findSOIMarker(file, frame_index + frame_size + 4);
Je teste et je te redis ça

2022-04-21 09:47 UTC, YannLocatelli commented on drivers/CoreVideo/source/CoreVideo.cpp
> +		frame_index = _corejpeg.findSOIMarker(file, frame_index + frame_size + 4);
Ca n'a pas d'impact sur la vidéo, donc j'ai retiré

2022-04-21 10:40 UTC, merged