:bricks: (fs): Add /fs directory structure
leka/LekaOS pull request #732
Opened 2022-04-26 22:20 UTC by ladislas

2022-04-29 15:19 UTC, YannLocatelli requested changes
Following files must be updated too:

- [ ] 14+ changes in `libs/BehaviorKit/source/BehaviorKit.cpp` + RobotController UT
- [ ] 1 in changes `libs/ConfigKit/include/Config.h` + its UT
- [ ] 4+ in changes `spikes/lk_lcd/main.cpp`

Note. The one in `app/bootloader/main.cpp` will be modified in incoming related PR #600

---

It is also possible to make these changes in another update, but `FirmwareKit` and `lk_file_reception` spike changes should go with those too to avoid confusion

2022-04-29 15:26 UTC, YannLocatelli commented on fs/README.md
> +| `/etc` | "Edit To Configure" - Contains system-wide configuration files, e.g. battery charging hysteresis, number of reboots before factory rollback, screen saver timeout, etc. Tout ce qu'on veut a
Some french here

2022-05-17 14:40 UTC, YannLocatelli commented on fs/usr/share/reboots
> +
Rename `global_reboots_counter`

2022-05-21 14:54 UTC, YannLocatelli commented
Rebased - Fix conflict of removed path in lk_lcd in #796

2022-06-13 15:21 UTC, ladislas commented on fs/etc/bootloader-reboots_limit
> +
set value

2022-06-13 15:27 UTC, ladislas commented on app/bootloader/main.cpp
> +	auto factory_reset_limit = Config {"/fs/etc/bootloader-reboots_limit", factory_reset::default_limit};
cherry pick after ec64b7e2160ccb2fb21e2abf43f5f8bf13db5d04 

update variable names

2022-06-15 10:13 UTC, closed without merging