Breath
leka/LekaOS pull request #738
Opened 2022-04-29 11:36 UTC by zozo976

Je n'ai pas pu tester mais je pense que çà devrait marcher. Si je ne me suis pas trompée, une inspiration/ expiration fait un peu plus d'une seconde

2022-05-02 15:23 UTC, HPezz requested changes
Belle première PR @zozo976,
Tu t'es bien approprié le code déjà existant. Ya quelques trucs à changer au niveau de la logique des animations, je t'ai mis des commentaires, on pourra en parler demain si t'as des questions.

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Breath.cpp
> +	static const auto sleep_time = rtos::Kernel::Clock::duration_u32 {20ms};
Tu peux pas utiliser de sleep pour les animations de LED, il faut te dire que utiliser un sleep revient à bloquer le code du robot le temps que tu met. Alors pour ton animation toute seule ça marche mais quand le robot devra bouger, recevoir des infos en bluetooth et tu bloques le robot, ça va poser problème. 

La solution c'est de jouer avec le "max" des fonctions increaseBrightness() et decreaseBrightness(). Essaie de le faire varier et tu verras les changements

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Breath.cpp
> +		rtos::ThisThread::sleep_for(sleep_time);
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Breath.cpp
> +		rtos::ThisThread::sleep_for(sleep_time);
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +#include "LogKit.h"
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +	_stage	 = 1;
```suggestion
	_stage	 = 0;
```
Meme remarque, décrementer tout de 1.

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +			// rtos::ThisThread::sleep_for(1000ms);case 4:
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +			_running = false;	//
```suggestion
			_running = false;
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +	static const auto sleep_time = rtos::Kernel::Clock::duration_u32 {10ms};
Meme remarque pour les sleep que Breath

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +void Heartbeat::increaseBrightness(uint8_t max, RGB color, rtos::Kernel::Clock::duration_u32 sleep_time)
```suggestion
void Heartbeat::increaseBrightness(uint8_t max, RGB color)
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +void Heartbeat::decreaseBrightness(uint8_t max, RGB color, rtos::Kernel::Clock::duration_u32 sleep_time)
```suggestion
void Heartbeat::decreaseBrightness(uint8_t max, RGB color)
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Breath.cpp
> +void Breath::increaseBrightness(uint8_t max, RGB color, rtos::Kernel::Clock::duration_u32 sleep_time)
```suggestion
void Breath::increaseBrightness(uint8_t max, RGB color)
```

2022-05-02 15:23 UTC, HPezz commented on libs/LedKit/source/animations/Breath.cpp
> +void Breath::decreaseBrightness(uint8_t max, RGB color, rtos::Kernel::Clock::duration_u32 sleep_time)
```suggestion
void Breath::decreaseBrightness(uint8_t max, RGB color)
```

2022-05-02 15:23 UTC, HPezz commented on spikes/CMakeLists.txt
> +
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on spikes/CMakeLists.txt
> +
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on spikes/CMakeLists.txt
> +
```suggestion
```

2022-05-02 15:23 UTC, HPezz commented on spikes/lk_heartbeat/main.cpp
> +		log_info("animation a été lancée");
Tu pourras faire un clean up de tes commentaires. Dans le spike on peut laisser les log mais à condition qu'ils soient clairs et en anglais

2022-05-04 08:04 UTC, HPezz reviewed
Ça me paraît good ! Bien joué
Ya quelques dernières modifs à faire en 2 secondes et t'es good

2022-05-04 08:04 UTC, HPezz commented on spikes/lk_heartbeat/main.cpp
> +	}
```suggestion
```

Si tu l'utilises pas tu peux supprimer cette fonction

2022-05-04 08:04 UTC, HPezz commented on libs/LedKit/source/animations/Breath.cpp
> +	_belt = &belt;
```suggestion
	_belt = &belt;
	_ears = &ears;
```

2022-05-04 08:04 UTC, HPezz commented on libs/LedKit/source/animations/AfraidRed.cpp
> +
Idéalement tu devrais pas avoir de changements sur ce fichier là, il te reste un petit espace à enlever

2022-05-04 08:04 UTC, HPezz commented on libs/LedKit/source/animations/Heartbeat.cpp
> +	_belt = &belt;
```suggestion
	_belt = &belt;
        _ears = &ears;
```

2022-10-25 12:52 UTC, closed without merging

2022-10-25 12:52 UTC, YannLocatelli commented
Follow up in

- #1081