:art: (videokit): Add onvideoDidEndCallback
leka/LekaOS pull request #784
Opened 2022-05-13 14:23 UTC by HPezz

2022-05-13 14:39 UTC, YannLocatelli requested changes
Une grosse question sur la redéfinition du callback + des suggestions de nom

2022-05-13 14:39 UTC, YannLocatelli commented on libs/VideoKit/source/VideoKit.cpp
> +			_onVideoDidEndCallback = {};
Etrange que cela

2022-05-13 14:39 UTC, YannLocatelli commented on libs/VideoKit/include/VideoKit.h
> +	std::function<void(void)> _onVideoDidEndCallback {};
```suggestion
	std::function<void()> _on_video_ended {};
```

2022-05-13 14:39 UTC, YannLocatelli commented on libs/VideoKit/source/VideoKit.cpp
> +			_onVideoDidEndCallback = {};
Pourquoi redéfinir le callback? (je ne parle pas de circonstances externes)

2022-05-13 14:49 UTC, YannLocatelli commented on libs/VideoKit/include/VideoKit.h
> +	std::function<void(void)> _onVideoDidEndCallback {};
+ ajouter `#include <functional>` dans l'en-tête (cf. clang-tidy)

2022-05-16 15:27 UTC, YannLocatelli reviewed
_Éventuellement_ ajouter cette nouvelle feature dans le spike pour qu'on puisse vérifier n'importe quand que ça fonctionne toujours 😉

- [ ] Validé sur le robot le ...

2022-05-16 15:27 UTC, YannLocatelli commented on libs/VideoKit/source/VideoKit.cpp
> +		_on_video_ended = onVideoDidEndCallback;
```suggestion
		_on_video_ended = onVideoEndedCallback;
```

ou si tu veux revenir comme avant

```suggestion
		_on_video_did_end = onVideoDidEndCallback;
```

2022-11-18 15:44 UTC, ladislas approved these changes
👍

2022-11-18 15:45 UTC, merged