mmyster/feature/add core io expander
leka/LekaOS pull request #792
Opened 2022-05-17 14:07 UTC by MMyster

- :art: (interface): Update interface::IOExpander
- :sparkles: (drivers): Add CoreIOExpander

2022-05-18 16:12 UTC, YannLocatelli requested changes

2022-05-18 16:12 UTC, YannLocatelli commented on drivers/CoreIOExpander/tests/CoreIOExpander_test.cpp
> +}
Les autres tests doivent aussi présenter les valeurs de registres

2022-05-18 16:12 UTC, YannLocatelli commented on drivers/CoreIOExpander/tests/CoreIOExpander_test.cpp
> +	}
Cette séquence se répète souvent, définis là en tant que fonction et passe lui des paramètres par rapport à des valeurs qui sont attendues

Par exemple:
Ajouter dans la classe CoreIOExpanderTest:
```cpp
	void expectedCallsSeqDir(uint8_t dir)
	{
		auto expected_dir_buffer = std::to_array<uint8_t>({0x00, dir});
		InSequence seq_dir;
		{
			EXPECT_CALL(mocki2c, write(i2c_address, _, 1, true)).Times(1);
			EXPECT_CALL(mocki2c, read(i2c_address, _, 2, false))
				.Times(1)
				.WillOnce(DoAll(SetArrayArgument<1>(std::begin(expected_dir_buffer), std::end(expected_dir_buffer)),
								Return(0)));
		}
	}
```

et l'appeler avec `expectedCallsSeqDir(0x00);`

2022-06-20 14:28 UTC, YannLocatelli approved these changes
Pour moi c'est bon ✅
C'est un sujet très complexe et tu l'as bien réussi en terme d'implémentation

Il reste toutefois encore un point en suspend: que signifie le terme `shadow`?

2022-06-20 14:28 UTC, YannLocatelli commented on drivers/CoreIOExpander/tests/CoreIOExpander_test.cpp
> +	auto expected_dir_buffer = std::to_array<uint8_t>({0x00, 0x01});
```suggestion
```

2022-06-20 14:28 UTC, YannLocatelli commented on drivers/CoreIOExpander/tests/CoreIOExpander_test.cpp
> +	auto expected_dir_buffer = std::to_array<uint8_t>({0x00, 0x01});
```suggestion
```

2022-06-22 07:51 UTC, ladislas reviewed
Premier passage, quelques modifications mais LGTM :

2022-06-22 07:51 UTC, ladislas commented on drivers/CoreIOExpander/include/CoreIOExpander.h
> +	} _shadow_register;
je comprends l'usage de ça, mais je suis pas hyper fan. 

ça me semble très `C` plus que `C++`

je préfère avoir la struct en struct et l'instantiation ensuite

```suggestion
	struct Registers {
		uint16_t iodir	 = 0xFFFF;
		uint16_t ipol	 = 0x0000;
		uint16_t gpinten = 0x0000;
		uint16_t defval	 = 0x0000;
		uint16_t intcon	 = 0x0000;
		uint16_t iocon	 = 0x0000;
		uint16_t gppu	 = 0x0000;
		uint16_t intf	 = 0x0000;
		uint16_t intcap	 = 0x0000;
		uint16_t gpio	 = 0x0000;
		uint16_t olat	 = 0x0000;
	};
	
	Registers _registers {};
```

2022-06-22 07:51 UTC, ladislas commented on drivers/CoreIOExpander/include/external/MCP23017.h
> +	constexpr inline uint16_t PA0 = 0x0001;
je préfère la forme:

```suggestion
	inline constexpr auto PA0 = uint16_t {0x0001};
```

2022-06-22 07:51 UTC, ladislas commented on drivers/CoreIOExpander/include/external/MCP23017.h
> +namespace registers {
singulier

```suggestion
namespace register {
```

2022-06-22 07:51 UTC, ladislas commented on drivers/CoreIOExpander/include/external/MCP23017.h
> +	constexpr inline uint8_t DIR_INPUT	= 0x01;
```suggestion
	inline constexpr auto output = uint8_t {0x00};
	inline constexpr auto input	= uint8_t {0x01};
```

2022-06-25 09:03 UTC, merged

2022-06-25 09:09 UTC, ladislas commented
replaced by #917