hugo/feature/Add Working state V2
leka/LekaOS pull request #816
Opened 2022-05-30 16:24 UTC by HPezz

- :sparkles: (behavior): Add Neutral behavior
- :sparkles: (RC & SM): Add Working state

2022-05-30 21:17 UTC, ladislas approved these changes
LGTM 👍 

quelques remarques/suggestions.

je pense que @YannLocatelli aura un regard intéressant aussi.

2022-05-30 21:17 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +			, sm::state::idle     + event<sm::event::command_received>                                   = sm::state::working
ici tu induis que si on reçoit une commande, on est forcément connecté.

c'est généralement vrai mais un bug peu se glisser et on peut "recevoir" une commande sans être connecté.

j'ajouterais un guard `is_ble_connected` ici.

2022-05-30 21:17 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +			, sm::state::sleeping + event<sm::event::command_received>                                   = sm::state::working
pareil ici, il faut guard que tu es connecté

2022-05-30 21:17 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +		_behaviorkit.neutral();
tu start le "working behavior" et dedans tu appelle le "neutral"

c'est bizarre. je garderai working partout.

2022-06-01 21:34 UTC, ladislas requested changes
tout est good pour moi 👍 

sauf la fonction `connectToBle` qui en l'état est un no go :x:

j'ai proposé des solutions en commentaire.

2022-06-01 21:34 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	void connectToBle() final { _is_ble_connected = true; }
je suis pas très fan de cette fonction qui n'a d'usage que pour les tests, pour plusieurs raisons:

1. le nom n'est pas adapté parce qu'elle ne fait pas ce qu'elle dit, qu'elle va faire, elle ne connecte pas au BLE.

le nom suivant serait plus adapté:

```suggestion
	void setBLEConnectionStatusToTrue() final { _is_ble_connected = true; }
```

2. la connection au BLE est orthogonale au RC. du coup ça fait bizarre d'avoir une dépendance si forte avec cette fonction qui donne l'impression que le RC peut décider ou non de connecter en BLE. Connecter à quoi d'ailleurs puisque c'est de toute manière pas le robot qui initie le truc.

dans le cas présent, et comme la connection est orthogonal, pourquoi dans les tests ne pas passer avant par un event "ble connection" afin de lancer `startConnectionBehavior` et d'être dans cet état de connection.

on peut aussi passer par `isBleConnected` + la sm directement pour avoir le statut avec  avec `sm.is(lksm::state::connected)`

```cpp
auto isBleConnected() -> bool final { return state_machine.is(lksm::state::working); }
```

ça serait même le plus smart maintenant qu'on a la machine orthogonale puisque comme pour `charging` on peut verifier qu'on est bien toujours `connected` avec un guard (j'imagine que BLEKit ou une de ses dépendances peut nous dire si on est connecté ou non)

2022-06-03 13:47 UTC, YannLocatelli approved these changes
LGTM 👌

2022-06-03 13:47 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateSleeping.cpp
> +	EXPECT_CALL(mock_motor_right, stop).Times(AtLeast(1));
Pas pour cette PR,

Regrouper tous ces expect_call dans une fonction (e.g. `MOCK_EXPECTEDCALLS_StopActuators`) pour ne pas trop complexifier le test

2022-06-03 13:57 UTC, HPezz commented on libs/RobotKit/tests/RobotController_test_stateSleeping.cpp
> +	EXPECT_CALL(mock_motor_right, stop).Times(AtLeast(1));
Je suis pour !

2022-06-03 14:18 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test.h
> +			EXPECT_CALL(timeout, onTimeout).WillOnce(GetCallback<interface::Timeout::callback_t>(&on_idle_timeout));
Juste en guise de note, ce callback n'est jamais appelé

2022-06-03 14:23 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test.h
> +			EXPECT_CALL(timeout, onTimeout).WillOnce(GetCallback<interface::Timeout::callback_t>(&on_idle_timeout));
Et point intéressant que tu relèves (puisque les tests se sont bien déroulés), c'est que la fonction n'est pas "utile"

Celle-ci:

https://github.com/leka/LekaOS/blob/7d64aec0843fbc773f39a0b5662569e70da370ec/libs/RobotKit/include/RobotController.h#L269-L270

2022-06-05 22:20 UTC, closed without merging