:sparkles: (drivers): Add CoreDACExpander
leka/LekaOS pull request #828
Opened 2022-06-03 12:46 UTC by MMyster

2022-06-23 13:51 UTC, ladislas requested changes
Premier passage

2022-06-23 13:51 UTC, ladislas commented on drivers/CoreDACTouch/include/external/MCP4728.h
> +	inline constexpr uint8_t writeAllInputRegister			  = 0x00;
même chose que dans #792 pour ici et pour tous les autres:

```suggestion
	inline constexpr auto writeAllInputRegister			  = uint8_t {0x00};
```

2022-06-23 13:51 UTC, ladislas commented on drivers/CoreDACTouch/source/CoreDACTouch.cpp
> +	command.at(0) = static_cast<uint8_t>((0xC0 & mcp4728::command::writeAllInputRegister) | (0x3F & value.at(0)));
les `&` et `|` je comprends pas ce que ça fait.

est-ce que tu peux avoir une petite fonction privée avec un nom explicite de l'opération.

2022-06-23 13:51 UTC, ladislas commented on drivers/CoreDACTouch/source/CoreDACTouch.cpp
> +		static_cast<uint8_t>((0xF8 & mcp4728::command::writeSpecificInputRegister) | (0x07 & ((0x03 & channel) << 1)));
pareil ici, pourquoi `0xF8 &` et pas autre chose?
pourquoi `(0x07 & ((0x03 & channel) << 1)))` et pas autre chose.

faut que le nom de l'opération soit explicite

2022-06-23 13:51 UTC, ladislas commented on drivers/CoreDACTouch/source/CoreDACTouch.cpp
> +		static_cast<uint8_t>((0xF8 & mcp4728::command::writeSpecificInputRegister) | (0x07 & ((0x03 & channel) << 1)));
et pareil pour les autres en dessous qui sont parfois les mêmes.

2022-06-23 13:51 UTC, ladislas commented on include/interface/drivers/DACTouch.h
> +class DACTouch
je rejoins @YannLocatelli !

il faut bien séparer les concepts:

- le `io_expander::AnalogOut`
- le calibrateur qui utilise le AnalogOut

2022-07-13 14:16 UTC, YannLocatelli commented
A supprimer/fermer : se référer à 

- #933

2022-07-13 14:59 UTC, closed without merging