:art: (libs): Update IOkit - add DigitalOut
leka/LekaOS pull request #829
Opened 2022-06-03 12:46 UTC by MMyster

2022-06-20 14:55 UTC, YannLocatelli requested changes
Rediscuter de la forme qu'on souhaite de la classe `IO`

En dehors de ça, ça a l'air bon selon moi

2022-06-20 14:55 UTC, YannLocatelli commented on libs/IOKit/include/internal/IO.h
> -	auto read() -> int
Quelle a été la nécessité de subdivisier `read` en 2 fonctions selon si c'est un pin entrant ou sortant?

Dans une utilisation courante, on se pose pas la question de savoir si c'est un pin qui est entrant ou sortant....

2022-06-20 14:55 UTC, YannLocatelli commented on libs/IOKit/include/internal/IO.h
> +	void writeOutput(int value) { _expander.writeOutputPin(_pin, value); }
De même pour la fonction `write` si c'est un pin dédié à l'entrée, on "n'écrit rien", sinon on écrit tout simplement

2022-06-20 14:55 UTC, YannLocatelli commented on libs/IOKit/include/internal/IO.h
> +	void setMode(PinMode mode) { _expander.setModeForPin(_pin, mode); }
D'une certaine manière il faut conserver l'information pour déterminer ce qu'est le pin, une entrée ou une sortie... ou les deux?

2022-06-20 14:55 UTC, YannLocatelli commented on libs/IOKit/include/internal/IO.h
> +	void setMode(PinMode mode) { _expander.setModeForPin(_pin, mode); }
Mais je comprends que la difficulté réside dans l'approche de DigitalIn et DigitalOut qui utilise tous les deux une même lib, IO, et qui se doit d'être assez général pour que les deux puissent être conforment

2022-06-20 15:04 UTC, YannLocatelli commented on libs/IOKit/tests/DigitalOut_test.cpp
> +	EXPECT_CALL(mockIOExpander, writeOutputPin(pin_number, 0x01)).Times(1);
Il y a un échec de test ici

En effet, dans cette PR, `mockIOExpander` est un mock de `IOExpander` or la méthode `writeOutputPin` n'a été modifié que dans `IO` donc n'est pas disponible pour `IOExpander`

2022-06-21 08:56 UTC, MMyster commented on libs/IOKit/tests/DigitalOut_test.cpp
> +	EXPECT_CALL(mockIOExpander, writeOutputPin(pin_number, 0x01)).Times(1);
`IOExpander` n'est pas encore intégré
Mais je pense qu'il faudrait que je revois la manière dont je répartis les PR

2022-06-26 14:12 UTC, ladislas approved these changes
LGTM 👍 

la division en readInput/readOutput me choque pas en l'état. Ca rend un truc assez complexe plus explicite à l'endroit où on le lit.

je trouve que 2 fonctions c'est plus simple qu'une variable membre qui stock le mode et un if/else dans une implémentation qui fait le choix.

on est sur du bas niveau, le côté explicite me plait bien.

2022-06-26 14:12 UTC, ladislas commented on libs/IOKit/include/internal/IO.h
> +	void writeOutput(int value) { _expander.writeOutputPin(_pin, value); }
dans l'interface de DigitalIn, il n'y a pas de write, donc la question ne se pose pas vraiment.

2022-06-30 12:45 UTC, merged