mmyster/feature/add touch sensor kit
leka/LekaOS pull request #830
Opened 2022-06-03 12:47 UTC by MMyster

- :sparkles: (libs): Add TouchSensorKit
- :sparkles: (spikes): Add lk_touch_sensor_kit

2022-06-20 15:56 UTC, YannLocatelli requested changes
Difficile de review en l'état

Ajoutes dans la description de la PR les autres PR qui doivent être merged avant de pouvoir merge celle-ci

2022-06-20 15:56 UTC, YannLocatelli commented on libs/TouchSensorKit/tests/TouchSensorKit_test.cpp
> +// Leka - LekaOS
Il faut ajouter TouchSensorKit dans `tests/unit/CMakeLists.txt`

2022-06-20 15:56 UTC, YannLocatelli commented on spikes/lk_touch_sensor_kit/CMakeLists.txt
> +# Leka - LekaOS
Ajouter le spik dans le fichier `spikes/CMakeLists.txt`

2022-06-20 15:56 UTC, YannLocatelli commented on libs/TouchSensorKit/CMakeLists.txt
> +# Leka - LekaOS
Ajouter la lib dans `libs/CMakeLists.txt`

2022-06-20 15:56 UTC, YannLocatelli commented on libs/TouchSensorKit/include/TouchSensorKit.h
> +class TouchSensorKit
On n'avait pas abordé le sujet, mais je pense que c'est intéressant de faire une classe intermédiaire qui s'appellerait TouchSensor pour un seul capteur.
Ainsi, les 6 capteurs seraient regroupés dans quelque chose de plus global/général que tu as nommé TouchSensorKit

2022-06-26 14:15 UTC, ladislas requested changes
premier passage avant les rebases

2022-06-26 14:15 UTC, ladislas commented on libs/TouchSensorKit/include/TouchSensorKit.h
> +class TouchSensorKit
oui je suis d'accord. 

ça pourrait être un `CoreTouchSensor`

2022-06-26 14:15 UTC, ladislas commented on libs/TouchSensorKit/include/internal/TouchSensorSystem.h
> +	constexpr inline uint16_t ear_left_input		 = leka::mcp23017::pin::PB5;
```suggestion
	inline constexpr auto ear_left_input		 = leka::mcp23017::pin::PB5;
```

2022-06-26 14:15 UTC, ladislas commented on libs/TouchSensorKit/include/internal/TouchSensorSystem.h
> +	constexpr inline uint16_t low	 = 0x00;
```suggestion
	inline constexpr auto low	 = uint16_t {0x00};
```
et pareil en dessous

2022-06-26 14:15 UTC, ladislas commented on libs/TouchSensorKit/include/internal/TouchSensorSystem.h
> +	constexpr inline uint16_t ear_left_input		 = leka::mcp23017::pin::PB5;
et pareil en dessous

2022-07-15 09:33 UTC, ladislas requested changes
un premier passage

2022-07-15 09:33 UTC, ladislas commented on libs/TouchSensorKit/include/TouchSensorKit.h
> +	auto belt_right_front_touched() const -> bool { return _state.belt_right_front_touched; };
ici ça demande, j'imagine, à l'usage de lire les différents capteurs en boucle avec un if/else assez long.

dans l'idéal il faudrait avoir:

- un `enum Position`

```cpp
enum class Position {
	ear_left,
	ear_right,
	belt_front_left,
	belt_front_right,
	belt_back_left,
	belt_back_right,
};
```

- un callback `onTouch(const Position pos)` que tu register depuis l'extérieur
- un thread ou event queue qui loop pour lui lire les sensors et appeler le callback le cas échéant

2022-07-28 16:29 UTC, YannLocatelli commented on libs/TouchSensorKit/source/TouchSensorKit.cpp
> +}
Pour l'`init` fait tout directement dans la fonction plutôt que de passer par l'intermédiaire. D'autant que c'est le genre de fonction qui ne sera appelé qu'une seule fois et que ça fait sens de les faire tous en même temps, à la suite.

```suggestion
void TouchSensorKit::init()
{
	_ear_left.init();
	_ear_right.init();
	_belt_left_back.init();
	_belt_left_front.init();
	_belt_right_back.init();
	_belt_right_front.init();
	
	_event_loop.registerCallback([this] { run(); });
}
```

2022-07-28 16:29 UTC, YannLocatelli commented on libs/TouchSensorKit/source/TouchSensorKit.cpp
> +void TouchSensorKit::calibrate(Position position)
Je me dis que la calibration d'un capteur est plus pertinent dans CoreTouchSensor plutôt que TouchSensorKit

Est-ce que tu peux le déplacer et l'adapter dans CoreTouchSensor?

2022-07-28 16:29 UTC, YannLocatelli commented on libs/TouchSensorKit/source/TouchSensorKit.cpp
> +			auto previousState = getLastStateAtPosition(position);
Tu es en train de revoir l'utilisation du run avec `EventLoop`, je te laisse me dire dès que c'est bon~

2022-07-28 16:29 UTC, YannLocatelli commented on libs/TouchSensorKit/include/TouchSensorKit.h
> +	std::array<bool, kNumberOfSensors> _state {};
J'imagine que c'est utilisé pour conserver les derniers états de chaque capteur
Je ne sais pas si c'est la meilleur approche, mais je vais y réfléchir encore un peu

Ce qui me gêne, pour faire court, c'est que l'on est pas à l'abri d'une inversion ou d'un bête copier coller et que les capteurs ne soient tout simplement pas les bons

2022-07-28 16:29 UTC, YannLocatelli commented on libs/TouchSensorKit/tests/TouchSensorKit_test.cpp
> +// Leka - LekaOS
🚧 Encore en cours... 🚧

2022-07-29 11:06 UTC, MMyster commented on libs/TouchSensorKit/include/external/TouchSensorSystem.h
> +// Leka - LekaOS
Nommer et lister les capteurs en les déclarant en variables globales

2022-07-29 12:04 UTC, MMyster commented on libs/TouchSensorKit/include/TouchSensorKit.h
> +	std::array<bool, kNumberOfSensors> _state {};
Est-ce que ce ne serait pas plus pertinent de créer 2 fonctions `updateState` et `getState` dans le CoreTouchSensor ?

2022-07-29 12:33 UTC, MMyster commented on libs/TouchSensorKit/source/TouchSensorKit.cpp
> +void TouchSensorKit::calibrate(Position position)
La calibration n'est pas propre au capteur dans le sens où c'est l'utilisateur qui détermine quelle valeur de sensibilité serait appropriée en fonction de son usage personnel

2022-07-29 12:36 UTC, MMyster commented on libs/TouchSensorKit/source/TouchSensorKit.cpp
> +void TouchSensorKit::calibrate(Position position)
Je le dis parce que le CoreTouchSensor est de type driver

2022-11-24 20:01 UTC, YannLocatelli commented on libs/TouchSensorKit/include/Position.h
> +};
@MMyster Why did this conversation is marked as resolved?

2022-11-24 20:01 UTC, YannLocatelli commented on libs/TouchSensorKit/source/TouchSensorKit.cpp
> +			state			   = currentState ? state | (1 << index) : state & ~(1 << index);
@MMyster Why did this conversation is marked as resolved?

2023-01-12 17:34 UTC, YannLocatelli commented
Usage of `std::map` seems to add 960 bytes

2023-01-13 13:19 UTC, ladislas approved these changes
LGTM 👍 

can the event queue changes be moved to another PR first?

2023-01-13 13:31 UTC, YannLocatelli commented on drivers/CoreEventQueue/include/CoreEventQueue.h
> +	void cancelLastCall() { _event_queue.cancel(_event_id); }
Yes, see

- #1252

2023-01-13 15:46 UTC, merged