:truck: (behavior): Rename charging behavior
leka/LekaOS pull request #870
Opened 2022-06-13 10:44 UTC by HPezz

2022-06-13 21:27 UTC, ladislas requested changes
le naming me va 👍  mais en relisant ce code, je le trouve trop complexe pour ce qu'il fait. j'ai mis un commentaire explicatif et la solution préférée.

2022-06-13 21:27 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +			_behaviorkit.chargingFullGreen();
en lisant là, je me demande pourquoi on a besoin de tant de petites fonctions "behavior" alors qu'on pourrait juste appeler le `videokit.display` ici.

je sais qu'il faut encapsuler mais dans le cas présent on ajoute 1 indirection, on en ajoute 5 qui font 5 choses différentes, donc 10 trucs à se souvenir pour savoir ce qu'il se passe quand on lit ces 8 lignes.

si on veut encapsuler, on fait une fonction `BehaviorKit::chargingAtLevel(uint8_t lvl)` avec les `if/else` dedans.
là ça fait une indirection qui encapsule proprement.

je vote pour le deuxième

2022-06-13 21:33 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +			_behaviorkit.chargingFullGreen();
à titre perso, je préfère aussi les conditions comme ça, je trouve ça plus lisible:

```cpp

void myFunc() {

    if (cond1) {
        doSomething();
        return;
    }

    if (cond2) {
        doSomethingElse();
        return;
    }

    doDefaultThing();

}
```

2022-06-14 10:50 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
> +			_behaviorkit.chargingFullGreen();
Comme dit à l'oral, je ne suis pas d'accord car il faut conserver le BehaviorKit simple et ne pas le complexifier en lui demandant autre chose que d'utiliser les actuateurs à savoir connaître le niveau de batteries.

Aussi cette lourdeur doit être présente, et je préfèrerais qu'elle soit dans le RobotController qui garde une réaction globale du robot quitte à être lourd plutôt que BehaviorKit qui est désormais bien léger et bien rodé dans sa fonction.

2022-06-14 22:01 UTC, ladislas requested changes
En repassant dessus, j'ai l'impression qu'on a un bug au niveau de l'affichage par rapport aux battery level, j'ai mis des commentaires explicatifs et j'ai fait des commits pour tester

2022-06-15 06:01 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
> +			_behaviorkit.chargingLow();
Effectivement, il y avait des conflits de rebase, on peut voir que ce qui a été retiré était bon

2022-06-15 07:32 UTC, HPezz commented on libs/RobotKit/include/RobotController.h
>  		}
C'est ça, ou plus simplement :

```cpp
void onChargingBehavior(uint8_t level)
{
        if (level < 25) {
		_behaviorkit.chargingEmpty();
	} else if (level < 50) {
		_behaviorkit.chargingLow();
	} else if (level < 75) {
		_behaviorkit.chargingMedium();
	} else if (level < 90) {
		_behaviorkit.chargingHigh();
	} else {
		_behaviorkit.chargingFull();
	}
}
```

2022-06-15 09:19 UTC, merged