hugo/feature/Add LedAnimation primitives
leka/LekaOS pull request #891
Opened 2022-06-20 16:30 UTC by HPezz

- :sparkles: (ledAnimation): Add sinPeriod primitive
- :dizzy: (ledanimation): Add Sinus animations example
- :white_check_mark: (tests): Add sinPeriod tests

2022-06-20 20:50 UTC, ladislas requested changes
je me suis permis une rapide review ;)

2022-06-20 20:50 UTC, ladislas commented on libs/LedKit/tests/LedKit_test_sinPeriod.cpp
> +	EXPECT_EQ(sinPeriod(period, 0, 0), expected_result);
ici et en dessous c'est des floats, donc il faut utiliser `EXPECT_FLOAT_EQ`

see https://google.github.io/googletest/reference/assertions.html#floating-point

2022-06-20 20:50 UTC, ladislas commented on libs/LedKit/CMakeLists.txt
>  endif()
garder le formatting d'origine avec les indentations en haut et les sauts de lignes pour les tests

2022-06-20 20:50 UTC, ladislas commented on libs/LedKit/include/LEDAnimation.h
> +	auto sinus		   = sin(x);
```suggestion
	auto sinus		   = std::sin(x);
```

c'est la même chose mais c'est plus sûr

2022-06-20 20:50 UTC, ladislas commented on libs/LedKit/include/LEDAnimation.h
> +	auto x			   = 2 * M_PI * (1.F / static_cast<float>(period)) * step + mapped_offset;
ici tu as pas rounding error? ou de implicit conversion?

2022-06-20 20:50 UTC, ladislas commented on libs/LedKit/include/animations/Sinus.h
> +	void stage3();
vu que tu testes des trucs différents dans chaque stage, je leur donnerai des noms plus sensés afin qu'on sache à quoi s'attendre

2022-06-20 20:50 UTC, ladislas commented on libs/LedKit/include/LEDAnimation.h
> +[[nodiscard]] inline auto sinPeriod(uint8_t period, uint8_t step, uint8_t offset) -> float
si ça c'est très mathématique, ça fait plus sens de le mettre dans `utils::math`

2022-06-21 22:06 UTC, ladislas approved these changes
LGTM now, modulo PI ;)

2022-06-21 22:06 UTC, ladislas commented on libs/LedKit/CMakeLists.txt
>  target_include_directories(LedKit
j'allais dire que le formatting était pas bon, mais j'ai vscode qui fait la même chose tout seul... c'est pénible et je trouve pas l'options...

2022-06-21 22:06 UTC, ladislas commented on libs/LedKit/source/animations/Sinus.cpp
> +			ColorFluctuationThreeLedSimpleSinusoid();
merci! super clair :) 👍

2022-10-25 12:52 UTC, YannLocatelli commented
Follow up in

- #1081

2022-10-25 12:52 UTC, closed without merging