sibylle/feature/create255RGB
leka/LekaOS pull request #913
Opened 2022-06-21 15:13 UTC by zozo976

- :sparkles: Add ColorPosition in ColorKit
- :white_check_mark: commit for an other branch

2022-06-21 21:24 UTC, ladislas requested changes
Première review 👍 

j'ai fait pas mal de retours, j'ai essayé d'être clair et détaillé, dis moi si des choses ne le sont pas pour toi, on peut en causer demain en daily dev.

quelques remarques:

- pas de std::vector en embarqué --> remplacer par std::span ou std::array
- remplacer les `array[i]` par `array.at(i)` qui ajoute du bound checking
- garder les noms des variables pour les for loop courtes (i, j, k, etc.)
- réfléchir à la return value qui est gigantesque, ça m'embête un peu comme ça. il faudrait que je vois comment c'est utilisé en pratique

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/include/ColorPosition.h
> +struct ColorPosition {
j'ai du mal à comprendre ce à quoi ça correspond. j'imagine que tu veux parler de la couleur correspondante à une position dans le gradient entre 0 et 255?

dans ce cas, je dirai plutôt:

```suggestion
struct GradientSpotColor {
```

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	auto first_input = input_colors[0];
```suggestion
	auto first_input = input_colors.front();
```

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	auto size		 = static_cast<uint8_t>(input_colors.size());
tu es sûre que tu as besoin du static_cast?

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	auto last_input = input_colors[size - 1];
```suggestion
	auto last_input = input_colors.back();
```

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	for (uint8_t index(0); index < first_input.position; index++) {
j'ai du mal à comprendre ce que font ces trois for loop.

peut être que tu peux les mettre dans des lambdas avec un nom clair

```cpp

auto fill_colors_with_??? = [return_colors]{ ... }

```

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	for (uint8_t index(0); index < first_input.position; index++) {
```suggestion
	for (auto i = 0; i < first_input.position; ++i) {
```

c'est toujours `++i` que tu veux, jamais `i++`-- tu connais la différence entre les deux?

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	for (uint8_t i(0); i < size - 1; i++) {
```suggestion
	for (auto i = 0; i < size - 1; ++i) {
```

pourquoi `size - 1`?

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +		for (uint8_t index(input_colors[i].position); index < input_colors[i + 1].position; index++) {
si c'est des for loop les un dans les autres, il faut utiliser `i, j, k` etc.

```suggestion
		for (auto j = input_colors[i].position; j < input_colors[i + 1].position; ++j) {
```

2022-06-21 21:24 UTC, ladislas commented on libs/ColorKit/source/ColorKit.cpp
> +	for (uint8_t index(last_input.position); index < 255; index++) {
```suggestion
	for (auto i = last_input.position; i < 255; ++i) {
```

2022-10-25 12:52 UTC, YannLocatelli commented
Follow up in

- #1081

2022-10-25 12:52 UTC, closed without merging