mmyster/feature/add lk touch sensor kit
leka/LekaOS pull request #926
Opened 2022-06-28 13:06 UTC by MMyster

- :art: (libs): Update IOkit - add DigitalOut
- :sparkles: (interface): Add DACTouch
- :sparkles: (drivers): Add CoreDACTouch
- :sparkles: (drivers): Add CoreTouchSensor
- :sparkles: (libs): Add TouchSensorKit
- :sparkles: (spikes): Add lk_touch_sensor_kit

2022-07-29 11:00 UTC, YannLocatelli requested changes
C'est une PR dédié au spike, s'il y a des changements en dehors, il faut les remettre les modifs de la lib dans la PR précédente

En dehors du rangement, tout est bien fait, bravo 👏

2022-07-29 11:00 UTC, YannLocatelli commented on spikes/lk_touch_sensor_kit/main.cpp
> +namespace TouchLed {
Ce spike est normalement dédié que aux capteurs de toucher et pas uniquement aux Toucher+LEDs ce qu'on ressent beaucoup ici

Essayes de segmenter ici en mettant dans un autre fichier (`TouchLed.h` et `TouchLed.cpp`) tout ce qui implique les LEDs en plus pour avoir [_voir le commentaire plus bas_]

2022-07-29 11:00 UTC, YannLocatelli commented on spikes/lk_touch_sensor_kit/main.cpp
> +	touch_sensor_kit.registerOnSensorReleased(turnOffLeds_func);
Avoir ici, dans le meilleur des cas bien sûr, 

```suggestion
	touch_sensor_kit.registerOnSensorTouched(TouchLed::turnOnLeds);
	touch_sensor_kit.registerOnSensorReleased(TouchLed::turnOffLeds);
```

ou

```suggestion
	touch_sensor_kit.registerOnSensorTouched(printSensorTouched);
	touch_sensor_kit.registerOnSensorReleased(printSensorReleased);
```

2022-07-29 11:00 UTC, YannLocatelli commented on spikes/lk_touch_sensor_kit/main.cpp
> +void calibration()
De même pour cette fonction, décliner selon l'utilisation des LEDs ou non:

- Toucher + logs
- Toucher + logs + LEDs

2023-01-13 13:19 UTC, ladislas approved these changes
LGTM 👍

2023-01-13 15:47 UTC, merged