hugo/feature/Refactor RFID
leka/LekaOS pull request #929
Opened 2022-07-05 17:09 UTC by HPezz

- :building_construction: (interface): Refactor & clean up interface RFIDReader
- :recycle: (drivers): Refactor & clean up CoreRFIDReader
- :recycle: (protocol): Add Protocol ISO14443 as an SM
- :recycle: (libs): Refactor & clean up RFIDKit with SM

2022-07-18 12:10 UTC, YannLocatelli requested changes
Beau boulot en tout cas ✨👏

Deux autres requêtes:

- [ ] Mettre à jour le spike RFID qui ne fonctionne plus, en cause le callback `onTagActivated` n'est pas définis → soit vérifier que `_on_tag_available_callback` n'est pas null, soit ajouter dans le spike définir le callback `onTagActivated`, soit les deux
- [ ] Déterminer quelle partie du code fait que l'écran ne fonctionne plus lorsqu'il s'agit de l'OS

2022-07-18 12:22 UTC, YannLocatelli commented on libs/RFIDKit/include/ISO14443A.h
> +			, sm::state::validating_tag   + boost::sml::on_exit<_> / ( sm::action::on_tag_valid {})      //TODO (@Hugo) Find a way to trigger set_tag_detection_mode before on_tag_valid instead of using it eve
Une première suggestion, un peu moche, est de faire confiance que `onTagValid` sera différé de quelques ms dans le `CoreRFIDReader`. C'est possible en appelant le corps actuel dans un event queue avec un délai.

2022-07-18 13:59 UTC, YannLocatelli commented on libs/RFIDKit/include/ISO14443A.h
> +			, sm::state::validating_tag   + boost::sml::on_exit<_> / ( sm::action::on_tag_valid {})      //TODO (@Hugo) Find a way to trigger set_tag_detection_mode before on_tag_valid instead of using it eve
En continuant de creuser, il semblerait que le soucis ne vienne pas du RFID en lui-même, mais du BufferedSerial.

Dans mon cas en inversant les actions, on retombe bien dans ton bug. Pour s'en sortir j'ai ajouté 2 lignes identiques:
```cpp
rtos::ThisThread::sleep_for(10ms);
```
juste après `_serial.read` et `_serial.write` de `setTagDetectionMode`

2022-07-18 14:06 UTC, YannLocatelli commented on drivers/CoreRFIDReader/source/CoreRFIDReader.cpp
>  				  rfid::command::frame::set_tag_detection_mode.size());
```suggestion
				  rfid::command::frame::set_tag_detection_mode.size());
		rtos::ThisThread::sleep_for(10ms);
```

2022-07-27 10:50 UTC, YannLocatelli reviewed
Pour tes tests

2022-07-27 10:50 UTC, YannLocatelli commented on libs/RFIDKit/tests/RFIDKit_test.cpp
> +	rfid_kit.onTagActivated(callback);
Ton test ici échoue car ton `callback == nullptr`
Définis lui un corps et ça résoudra le problème

```suggestion
	callback = [](MagicCard &) { ; };
	rfid_kit.onTagActivated(callback);
```

2022-07-27 10:50 UTC, YannLocatelli commented on libs/RFIDKit/source/RFIDKit.cpp
> +		if (isTagSignatureValid(tag)) {
Il manque le second test où la signature n'est pas bonne:

Reprends le test `registerMagicCardCallbackTagValidCallbackSet` ou `registerMagicCardCallbackTagValidCallbackNotSet`, change le début de `data` tout simplement

2022-07-27 14:17 UTC, ladislas commented on drivers/CoreRFIDReader/source/CoreRFIDReader.cpp
>  	std::array<uint8_t, 2> buffer {};
je pense que tu peux t'abstenir d'utiliser un buffer et un std::copy qui ne font que complexifier la chose et simplement utiliser std::equal

comme ici: https://gcc.godbolt.org/z/7rcj4913a

2022-07-27 14:20 UTC, ladislas commented on drivers/CoreRFIDReader/source/CoreRFIDReader.cpp
> +	if (_answer_size != rfid::expected_answer_size::tag_detection) {
est-ce que tu as vraiment besoin de ce check?

ça me gène que ça utilise comme ça le `_answer_size` parce que c'est une interface publique et que tu peux l'appeler quand tu veux.

2022-07-27 14:27 UTC, ladislas commented on drivers/CoreRFIDReader/source/CoreRFIDReader.cpp
> +		setGainAndModulationISO14443A();
ici je ferai les serial write directement pour ne pas avoir les fonctions ISOblablabla dans l'interface même privée.

2022-07-29 10:40 UTC, YannLocatelli reviewed
Review uniquement sur les UTs

Ce ne sont que des suggestions d'améliorations

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +	}
Partie non utilisée

```suggestion
```

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +	std::function<void()> callbackSigio {};
Transforme tes callbacks callbackDetected et callbackReadable en MockFunction, tu verras qu'il y a des appels en plus et ça permettra d'avoir plus de contrôle sur ce qui se passe

```suggestion
	testing::MockFunction<void()> callback_detected;
	testing::MockFunction<void(rfid::Tag)> callback_readable;
	std::function<void()> callbackSigio {};
```

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +	std::function<void()> callbackSigio {};
Rappel: lors du register, il ne faut pas passer la callback mais appeler `AsStdFunction()`

Exemple:  
`reader.registerOnTagDetectedCallback(callbackDetected.AsStdFunction());`

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +	std::array<uint8_t, 2> set_gain_and_modulation_success_answer = {0x00, 0x00};
N'est pas utilisé?

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +	;
```suggestion
```

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +					rfid::command::frame::set_tag_detection_mode[14], rfid::command::frame::set_tag_detection_mode[15]);
Comme il n'y pas de valeur brute à préciser et que tout est déjà dans un array spécifique

```suggestion
	const auto expected_values = testing::ElementsAreArray(rfid::command::frame::set_tag_detection_mode);
```

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +	// void SetUp() override {}
Pour éviter de le refaire dans la plupart des tests

```suggestion
	void SetUp() override
	{
		reader.registerOnTagReadableCallback(callbackReadable.AsStdFunction());
		reader.registerOnTagDetectedCallback(callbackDetected.AsStdFunction());
		EXPECT_CALL(mockBufferedSerial, sigio).WillOnce(SaveArg<0>(&callbackSigio));
		reader.init();
	}
```

2022-07-29 10:40 UTC, YannLocatelli commented on drivers/CoreRFIDReader/tests/CoreRFIDReader_test.cpp
> +TEST_F(CoreRFIDReaderTest, setCommunicationProtocolFailedOnAnswerTooBig)
Je ne vois pas la différence niveau `EXPECT` entre le test réussi au-dessus, et ceux qui échouent

Pourquoi as-tu ajouté ces tests?

2022-07-29 11:46 UTC, YannLocatelli commented
> Déterminer quelle partie du code fait que l'écran ne fonctionne plus lorsqu'il s'agit de l'OS

Passer la callback en argument de onTagActivated() en const reference

2022-07-29 12:14 UTC, YannLocatelli reviewed
Je sais plus si je l'ai mis, mais à la lecture tout me semble fluide et rien ne me fait tiquer en me disant "ça ne devrait pas être là", c'est cool ✨

Toute fonctionne donc j'ai juste quelques suggestions d'améliorations pour l'implémentation ✅

2022-07-29 12:14 UTC, YannLocatelli commented on libs/RFIDKit/source/RFIDKit.cpp
> +			_card = MagicCard {tag.data[5]};
Il faudrait aussi un test pour vérifier, ça va impliquer de se renseigner sur le MockFunction pour "étudier" la valeur de la MagicCard

2022-07-29 12:14 UTC, YannLocatelli commented on libs/RFIDKit/source/RFIDKit.cpp
> +			_card = MagicCard {tag.data[5]};
J'ai trouvé ça https://google.github.io/googletest/gmock_cook_book.html#QuickNewActions

Ca devrait permettre de traiter ce qui passe par le `mock_callback` et donc de vérifier que la magic card a bien le même id

2022-08-17 16:00 UTC, merged

2023-05-17 23:34 UTC, Lenzo1 approved these changes
Let's go