mmyster/feature/quad digital to analog converter
leka/LekaOS pull request #933
Opened 2022-07-10 19:37 UTC by MMyster

- :sparkles: (interface): Add QDAC
- :sparkles: (drivers): Add CoreQDAC

2022-07-15 09:07 UTC, ladislas requested changes
premier passage 👍

2022-07-15 09:14 UTC, YannLocatelli requested changes

2022-07-15 09:14 UTC, YannLocatelli commented on drivers/CoreQDAC/source/CoreQDAC.cpp
> +		_reg.at(ch).vref = _eep.at(ch).vref = 1 & (data >> (3 - ch));
I know it is more compact, but can you set it in 2 lines?

2022-07-15 11:50 UTC, MMyster commented on drivers/CoreQDAC/source/CoreQDAC.cpp
> +void CoreQDACMCP4728::write(uint8_t channel, uint16_t data, bool b_eep)
`true` : écriture dans les inputs registers + sauvegarde dans l'EEPROM Memory
`false` : écriture dans les inputs registers seulement

Channel c'est bien ça

2022-07-15 11:59 UTC, MMyster commented on drivers/CoreQDAC/include/CoreQDAC.h
> +	void sequentialWrite();
fastWrite : écriture séquentielle vers les inputs registers 
multiWrite : comme fastWrite mais avec possibilité de définir le ou les channels
sequential : écriture séquentielle vers les inputs registers + EEPROM Memory à partir d'un channel défini
single : écriture "unique" vers un input register + EEPROM Memory

Voir https://www.dropbox.com/home/Development/hardware/electronics/datasheets?preview=Aceltis-Flex-DAC-MCP4728.pdf
Page 34

Les `data`, ce sont les tableaux en variables privées

2022-07-15 12:05 UTC, MMyster commented on include/interface/drivers/QDAC.h
> +	virtual auto read(uint8_t channel, bool b_eep = false) -> uint16_t	   = 0;
b_eep stands for "boolean eeprom"... I saw some similar examples somewhere

2022-07-15 12:08 UTC, MMyster commented on include/interface/drivers/QDAC.h
> +	virtual auto read(uint8_t channel, bool b_eep = false) -> uint16_t	   = 0;
It is 12-Bit Voltage Output DAC. So we need at least 12 bits for data

2022-07-19 12:53 UTC, YannLocatelli commented on include/interface/drivers/QDAC.h
> +	virtual auto read(uint8_t channel, bool b_eep = false) -> uint16_t	   = 0;
Ok, clear 👌

2022-07-20 10:14 UTC, YannLocatelli approved these changes
C'est bon pour moi en l'état, Bravo! ✅

Il me reste le spike à valider et tout ce qui sera QDAC sera bon selon moi :)

2022-07-20 10:14 UTC, YannLocatelli commented on include/interface/drivers/QDAC.h
> +		virtual auto read(Channel channel, bool eeprom = false) -> uint16_t		= 0;
Merci de confirmer si c'est bien ces actions qui en découle selon la valeur booléenne~
```suggestion
		virtual void write(Channel channel, uint16_t data, bool save_in_eeprom = false) = 0;
		virtual auto read(Channel channel, bool load_from_eeprom = false) -> uint16_t		= 0;
```

2022-07-20 10:14 UTC, YannLocatelli commented on include/interface/drivers/QDAC.h
> +		virtual void write(Channel channel, uint16_t data, bool eeprom = false) = 0;
Un commentaire aussi pour la notion d'EEPROM pour tous les QDAC: est-ce qu'ils en possèdent tous un?

Mon opinion est que non, et que celui qu'on a cet avantage de posséder une mémoire en plus.

Dans l'immédiat, ça ne me gêne pas de le laisser, on pourra y revenir une fois que tout le TouchKit sera fonctionnel~

2022-08-17 17:01 UTC, ladislas requested changes
merci @MMyster! C'est pas mal du tout!

quelques retours sur la forme et changements pour rendre les choses plus lisibles et compréhensible pour les gens qui ne savent pas ce qui se passe

2022-08-17 17:01 UTC, ladislas commented on drivers/CoreQDAC/source/CoreQDAC.cpp
> +	command.at(1) = static_cast<uint8_t>((0x0F & data) << 4);
pareil ici

2022-08-18 16:05 UTC, ladislas commented
Patch containing `fastWrite` and `sequentialWrite`

[2022_08_18-QDAC-Patch.diff.zip](https://github.com/leka/LekaOS/files/9375524/2022_08_18-QDAC-Patch.diff.zip)
 
```diff
diff --git a/drivers/CMakeLists.txt b/drivers/CMakeLists.txt
index 26e1b4db..f3154b56 100644
--- a/drivers/CMakeLists.txt
+++ b/drivers/CMakeLists.txt
@@ -39,3 +39,6 @@ add_subdirectory(${DRIVERS_DIR}/CoreMotor)
 
 # Touch drivers
 add_subdirectory(${DRIVERS_DIR}/CoreIOExpander)
+add_subdirectory(${DRIVERS_DIR}/CoreQDAC)
+
+
diff --git a/drivers/CoreQDAC/CMakeLists.txt b/drivers/CoreQDAC/CMakeLists.txt
new file mode 100644
index 00000000..a2aa8949
--- /dev/null
+++ b/drivers/CoreQDAC/CMakeLists.txt
@@ -0,0 +1,28 @@
+# Leka - LekaOS
+# Copyright 2022 APF France handicap
+# SPDX-License-Identifier: Apache-2.0
+
+add_library(CoreQDAC STATIC)
+
+target_include_directories(CoreQDAC
+	PUBLIC
+		include
+)
+
+target_sources(CoreQDAC
+	PRIVATE
+		source/CoreQDAC.cpp
+)
+
+target_link_libraries(CoreQDAC
+	mbed-os
+	CoreI2C
+)
+
+if (${CMAKE_PROJECT_NAME} STREQUAL "LekaOSUnitTests")
+
+	leka_unit_tests_sources(
+		tests/CoreQDAC_test.cpp
+	)
+
+endif()
diff --git a/drivers/CoreQDAC/include/CoreQDAC.h b/drivers/CoreQDAC/include/CoreQDAC.h
new file mode 100644
index 00000000..b4046d07
--- /dev/null
+++ b/drivers/CoreQDAC/include/CoreQDAC.h
@@ -0,0 +1,55 @@
+// Leka - LekaOS
+// Copyright 2022 APF France handicap
+// SPDX-License-Identifier: Apache-2.0
+
+#pragma once
+
+#include <array>
+#include <span>
+
+#include "external/MCP4728.h"
+#include "interface/drivers/I2C.h"
+#include "interface/drivers/QDAC.h"
+
+namespace leka {
+
+class CoreQDACMCP4728 : public interface::QDAC
+{
+  public:
+	CoreQDACMCP4728(interface::I2C &i2c, uint8_t address) : _i2c(i2c), _address(address) {};
+
+	void init() final;
+	void write(Channel channel, uint16_t data, bool eeprom = false) final;
+	void writeAllChannels(uint16_t data, bool eeprom = false);
+
+	auto read(Channel channel, bool eeprom = false) -> uint16_t final;
+
+  private:
+	void fastWrite();
+	void multiWrite(uint8_t channel);
+	void sequentialWrite(uint8_t starting_channel);
+	void singleWrite(uint8_t channel);
+
+	void setVoltageReference(uint8_t data);
+	void setPowerDown(uint8_t data);
+	void setGain(uint8_t data);
+
+	void readInputRegistersAndMemory();
+
+	interface::I2C &_i2c;
+	uint8_t _address;
+
+	struct QDACInputData {
+		uint8_t vref  = 0x00;
+		uint8_t pd	  = 0x00;
+		uint8_t gain  = 0x00;
+		uint16_t data = 0x0000;
+	};
+
+	std::array<QDACInputData, 4> _tx_registers {};
+	std::array<QDACInputData, 4> _tx_eeprom {};
+	std::array<QDACInputData, 4> _rx_registers {};
+	std::array<QDACInputData, 4> _rx_eeprom {};
+};
+
+}	// namespace leka
diff --git a/drivers/CoreQDAC/include/external/MCP4728.h b/drivers/CoreQDAC/include/external/MCP4728.h
new file mode 100644
index 00000000..493fd4ea
--- /dev/null
+++ b/drivers/CoreQDAC/include/external/MCP4728.h
@@ -0,0 +1,114 @@
+// Leka - LekaOS
+// Copyright 2022 APF France handicap
+// SPDX-License-Identifier: Apache-2.0
+
+// Source: https://www.dropbox.com/home/Development/hardware/electronics/datasheets?preview=Aceltis-Flex-DAC-MCP4728.pdf
+
+#pragma once
+
+#include <cstddef>
+
+#include "cstdint"
+
+namespace leka::mcp4728 {
+
+namespace command {
+
+	inline constexpr auto fast_write	   = uint8_t {0x00};
+	inline constexpr auto multi_write	   = uint8_t {0x40};
+	inline constexpr auto sequential_write = uint8_t {0x50};
+	inline constexpr auto single_write	   = uint8_t {0x58};
+
+	inline constexpr auto set_vref		 = uint8_t {0x80};
+	inline constexpr auto set_power_down = uint8_t {0xA0};
+	inline constexpr auto set_gain		 = uint8_t {0xC0};
+
+	namespace read {
+		inline constexpr auto buffer_size = std::size_t {24};
+	}	// namespace read
+
+}	// namespace command
+
+namespace channel {
+
+	inline constexpr auto A = uint8_t {0x00};
+	inline constexpr auto B = uint8_t {0x01};
+	inline constexpr auto C = uint8_t {0x02};
+	inline constexpr auto D = uint8_t {0x03};
+
+}	// namespace channel
+
+namespace data {
+
+	namespace voltage_reference {
+
+		inline constexpr auto Vdd = uint8_t {0x00};
+		namespace internal {
+			namespace channel {
+				inline constexpr auto A = uint8_t {0x08};
+				inline constexpr auto B = uint8_t {0x04};
+				inline constexpr auto C = uint8_t {0x02};
+				inline constexpr auto D = uint8_t {0x01};
+			}	// namespace channel
+			inline constexpr auto all = uint8_t {0x0f};
+		}	// namespace internal
+
+	}	// namespace voltage_reference
+
+	namespace power_down {
+
+		inline constexpr auto normal = uint8_t {0x00};
+
+		namespace channel {
+			namespace A {
+				inline constexpr auto normal		= uint8_t {0x00};
+				inline constexpr auto powerDown1K	= uint8_t {0x40};
+				inline constexpr auto powerDown100K = uint8_t {0x80};
+				inline constexpr auto powerDown500K = uint8_t {0xC0};
+			}	// namespace A
+
+			namespace B {
+				inline constexpr auto normal		= uint8_t {0x00};
+				inline constexpr auto powerDown1K	= uint8_t {0x10};
+				inline constexpr auto powerDown100K = uint8_t {0x20};
+				inline constexpr auto powerDown500K = uint8_t {0x30};
+			}	// namespace B
+
+			namespace C {
+				inline constexpr auto normal		= uint8_t {0x00};
+				inline constexpr auto powerDown1K	= uint8_t {0x04};
+				inline constexpr auto powerDown100K = uint8_t {0x08};
+				inline constexpr auto powerDown500K = uint8_t {0x0C};
+			}	// namespace C
+
+			namespace D {
+				inline constexpr auto normal		= uint8_t {0x00};
+				inline constexpr auto powerDown1K	= uint8_t {0x01};
+				inline constexpr auto powerDown100K = uint8_t {0x02};
+				inline constexpr auto powerDown500K = uint8_t {0x03};
+			}	// namespace D
+
+		}	// namespace channel
+	}		// namespace power_down
+
+	namespace gain {
+
+		namespace x1 {
+			inline constexpr auto all = uint8_t {0x00};
+		}
+
+		namespace x2 {
+			namespace channel {
+				inline constexpr auto A = uint8_t {0x08};
+				inline constexpr auto B = uint8_t {0x04};
+				inline constexpr auto C = uint8_t {0x02};
+				inline constexpr auto D = uint8_t {0x01};
+			}	// namespace channel
+			inline constexpr auto all = uint8_t {0x0f};
+		}	// namespace x2
+
+	}	// namespace gain
+
+}	// namespace data
+
+}	// namespace leka::mcp4728
diff --git a/drivers/CoreQDAC/source/CoreQDAC.cpp b/drivers/CoreQDAC/source/CoreQDAC.cpp
new file mode 100644
index 00000000..2547d602
--- /dev/null
+++ b/drivers/CoreQDAC/source/CoreQDAC.cpp
@@ -0,0 +1,153 @@
+// Leka - LekaOS
+// Copyright 2022 APF France handicap
+// SPDX-License-Identifier: Apache-2.0
+
+#include "CoreQDAC.h"
+#include <array>
+
+#include "MemoryUtils.h"
+
+using namespace leka;
+
+void CoreQDACMCP4728::init()
+{
+	setVoltageReference(mcp4728::data::voltage_reference::Vdd);
+	setPowerDown(mcp4728::data::power_down::normal);
+	setGain(mcp4728::data::gain::x1::all);
+}
+
+void CoreQDACMCP4728::write(Channel channel, uint16_t data, bool eeprom)
+{
+	auto ch = static_cast<uint8_t>(channel);
+	if (eeprom) {
+		_tx_registers.at(ch).data = data;
+		_tx_eeprom.at(ch).data	  = data;
+		singleWrite(ch);
+	} else {
+		_tx_registers.at(ch).data = data;
+		multiWrite(ch);
+	}
+}
+
+void CoreQDACMCP4728::writeAllChannels(uint16_t data, bool eeprom)
+{
+	if (eeprom) {
+		for (uint8_t ch = mcp4728::channel::A; ch <= mcp4728::channel::D; ch++) {
+			_tx_registers.at(ch).data = data;
+			_tx_eeprom.at(ch).data	  = data;
+		}
+		sequentialWrite(mcp4728::channel::A);
+	} else {
+		for (uint8_t ch = mcp4728::channel::A; ch <= mcp4728::channel::D; ch++) {
+			_tx_registers.at(ch).data = data;
+		}
+		fastWrite();
+	}
+}
+
+auto CoreQDACMCP4728::read(Channel channel, bool eeprom) -> uint16_t
+{
+	auto ch = static_cast<uint8_t>(channel);
+	readInputRegistersAndMemory();
+	return eeprom ? _rx_eeprom.at(ch).data : _rx_registers.at(ch).data;
+}
+
+void CoreQDACMCP4728::fastWrite()
+{
+	auto command = std::array<uint8_t, 8> {};
+	for (uint8_t ch = mcp4728::channel::A; ch <= mcp4728::channel::D; ch++) {
+		command.at(ch * 2)	   = static_cast<uint8_t>(m [...]

2022-08-18 16:14 UTC, ladislas approved these changes

2022-08-18 16:14 UTC, merged