:art: Reorganize code Game TouchSpeed spike
leka/LekaOS pull request #937
Opened 2022-07-13 10:41 UTC by zozo976

2022-07-15 10:00 UTC, ladislas commented on spikes/lk_game_touch_speed/LedManager.h
> +	void turnOnCaptor(uint8_t indexCaptor, leka::RGB color);
en anglais c'est pas "captor", c'est "sensor"

mais je comprends pas pourquoi le LedManager il manage aussi les sensors.

il faut évidemment séparer les deux!

2022-07-15 10:00 UTC, ladislas commented on spikes/lk_game_touch_speed/LedManager.h
> +	void setRandomCaptorWithColor(uint8_t captorNumber);
pareil "captor" --> "sensor" et même remarque sur le scope de la classe avec LED + Sensors

2022-07-15 10:05 UTC, ladislas commented on spikes/lk_game_touch_speed/LedManager.h
> +	void turnOffBeltLeftFront();
c'est bien d'avoir fait des fonctions séparées avec des rôles bien clair à chaque fois.

comme dit ici, ça vaut le coup parfois d'avoir un `enum` pour ce genre de chose:

https://github.com/leka/LekaOS/pull/830#discussion_r921992039

ce qui te permet de faire après:

```cpp
void turnOn(const Position pos, RGB color);

// et à l'usage

led_manager.turnOn(Position::ear_left, RGB::red);
```

2022-07-15 10:06 UTC, ladislas commented on spikes/lk_game_touch_speed/Level.cpp
> +	int sinceRoundBegin = 0;
`sinceRoundBegin` quoi? du temps? un counter? des réussites? des erreurs? c'est pas clair

2022-07-15 10:07 UTC, ladislas commented on spikes/lk_game_touch_speed/Level.cpp
> +namespace leds {
ça n'a pas de raison d'être dans le namespace `leds`

2022-07-15 10:12 UTC, ladislas commented on spikes/lk_game_touch_speed/Level.cpp
> +	} while (!(_currentRound.is_target_touched()) && (sinceRoundBegin > _maximumDuration));
ça tu peux le sortir dans un lambda que tu mets au dessus et que tu appelles ensuite:

```cpp
auto keep_playing = [&](){ 
	auto target_not_touched = !_currentRound.is_target_touched();
	auto time_still_available = sinceRoundBegin > _maximumDuration;

	auto ret = target_not_touched && time_still_available;

	return ret;
};

do {
	// ...
} while (keep_playing());
```

ça rend le code beaucoup plus clair:

- on comprend que la condition c'est `keep_playing`
- on peut aller voir ce que veut dire `keep_playing`
- dans `keep_playing`, j'ai séparé les conditions pour que ce soit facile à comprendre et à mettre à jour si besoin, j'ai donné des noms sensées même à des choses simples

c'est une bon exemple d'usage des lambdas

2022-07-15 10:15 UTC, ladislas commented on spikes/lk_game_touch_speed/Level.cpp
> +		}
ici si tu perds une fois, tu repars de zéro, c'est bien ça?

je sortirai le `playOnce` du `if` parce que c'est pas une simple condition, c'est un truc qui dure très longtemps.

```suggestion
		auto round_won = playOnce();
		if (round_won) {
			++_score;
			log_info("Round won, score = %i", _score);
		} else {
			_score = 0;
			log_info("Round lost, score = %i", _score);
		}
```

2022-07-15 10:15 UTC, ladislas commented on spikes/lk_game_touch_speed/Level.h
> +	static const uint8_t scoreToWinLevel  = 5;
pourquoi c'est public ça?

2022-07-15 10:22 UTC, ladislas commented on spikes/lk_game_touch_speed/Level.h
> +	Level(LedManager &ledManager, uint8_t number, Round &currentRound, leka::TouchSensorKit &touchSensorKit)
`number`? je comprends pas ce que c'est. le nombre de rounds?

et je comprends pas le `currentRound` non plus

est-ce que dans un level tu as plusieurs rounds ou c'est l'inverse, dans un round tu as plusieurs levels?

2022-07-15 10:23 UTC, ladislas commented on spikes/lk_game_touch_speed/Random8.cpp
> +auto random8(uint8_t min, uint8_t max) -> uint8_t
ça c'est du code duplication --> il faut utiliser celui qui existe déjà dans les leds.

si ça fait bizarre, il faut le mettre plus haut dans la hiérarchie par exemple dans utils::math

2022-07-15 10:25 UTC, ladislas commented on spikes/lk_game_touch_speed/Round.cpp
> +	if (touched > 5 || touched < 0) {
si y a un warning et que c'est forcément > 0 pourquoi tu gardes la condition. Il faut la retirer

2022-07-15 10:25 UTC, ladislas commented on spikes/lk_game_touch_speed/Round.cpp
> +	if (touched > 5 || touched < 0) {
pareil ici

2022-07-15 10:27 UTC, ladislas commented on spikes/lk_game_touch_speed/Round.cpp
> +}
une fonction qui commence par `is_` induit bien un `bool` en return type.

par contre je ne comprends pas pourquoi ça r'envoie `_win`? je m'attends à voir la logique dans cette fonction. par ce que là je sais pas comment _win a été set, ni la valeur qu'il y a dedans. 

est-ce que tu peux être touched et pas win?

2022-07-15 10:27 UTC, ladislas commented on spikes/lk_game_touch_speed/Round.cpp
> +void Round::setTouched()
ça c'est quoi?

2022-07-15 10:50 UTC, zozo976 commented on spikes/lk_game_touch_speed/LedManager.h
> +	void turnOnCaptor(uint8_t indexCaptor, leka::RGB color);
Je pense que le nom de ma fonction est mal choisi. Le ledManager ne gère pas les sensors. Un numéro de capteur aléatoire est généré au niveau d'un Round au sein de la fonction choseRandomCaptorAsTarget(). Le seul rôle de cette fonction turnOnCaptor() est d'allumer le groupe de leds correspondant.

2022-07-15 10:54 UTC, zozo976 commented on spikes/lk_game_touch_speed/LedManager.h
> +	void setRandomCaptorWithColor(uint8_t captorNumber);
Je pense aussi que mon nom de fonction porte à confusion. Avant que turnOnCaptor(ou turnOnSensor() ) allume le bon groupe de led. Elles sont settées par cette fonction.

2022-07-15 10:59 UTC, zozo976 commented on spikes/lk_game_touch_speed/LedManager.h
> +	void turnOnCaptor(uint8_t indexCaptor, leka::RGB color);
Mais par contre la classe a quand même besoin de connaître des informations sur les sensors pour savoir lesquels allumer

2022-07-15 11:09 UTC, zozo976 commented on spikes/lk_game_touch_speed/Round.cpp
> +void Round::setTouched()
Chaque groupe de capteur a un numéro qui lui est associé. Celui qui correspond à l'oreille gauche porte le numéro 0 et celui de la ceinture avant à gauche le numéro 5 par exemple. En fonction du signal récupéré par les capteurs. L'attribut _touched de Round récupère la valeur du groupe de capteur touché.
C'est à cela que sert setTouched()

2022-07-15 12:05 UTC, ladislas commented on spikes/lk_game_touch_speed/LedManager.h
> +	void turnOnCaptor(uint8_t indexCaptor, leka::RGB color);
alors faut changer avec un nom qui correspond à ce que tu fais. peut être parle de zone plus que de sensor

position comme j'ai mis plus bas marche bien aussi.

mais là on comprend pas.

2022-07-15 12:05 UTC, ladislas commented on spikes/lk_game_touch_speed/LedManager.h
> +	void setRandomCaptorWithColor(uint8_t captorNumber);
pareil, il faut changer alors.

2022-07-15 12:05 UTC, ladislas commented on spikes/lk_game_touch_speed/Round.cpp
> +}
la target c'est la zone bleue qu'il faut toucher?

et c'est "lose" pas "loose"

2022-07-15 12:05 UTC, ladislas commented on spikes/lk_game_touch_speed/Round.cpp
> +void Round::setTouched()
quand il y a un `set` il faut un argument.

dans le cas là, je sais pas ce que ça fait mais c'est plutôt "updateTouchState" (j'aime pas ce nom)

2022-07-25 16:01 UTC, HPezz requested changes
Voilà pour ma première review, tu t'améliores. Il y a encore des progrès à faire sur la complexité de ton code, des fonctions peuvent n'être qu'une ligne ou sont des redondances, et sur cela, seule une bonne prise de recul pourra te faire prendre conscience de ce que tu fais. On en discute demain pour voir comment faire fitter tout ça dans une architecture analogue à LedKit

2022-07-26 09:24 UTC, zozo976 commented on drivers/CoreTouchSensor/tests/CoreTouchSensor_test.cpp
>  // SPDX-License-Identifier: Apache-2.0
En fait les tests sont obsolètes mais ce n'est pas à cause de ce que j'ai ajouté. Par exemple il n'y a plus du tout de CoreDacTouch dans la nouvelle implémentation. Ils passent le make mais pas les make ut.

2022-10-11 13:22 UTC, closed without merging