mmyster/feature/lk quad digital to analog converter
leka/LekaOS pull request #940
Opened 2022-07-19 11:13 UTC by MMyster

- :sparkles: (interface): Add QDAC
- :sparkles: (drivers): Add CoreQDAC
- :art: (drivers): Update QDAC
- :art: (drivers): Update QDAC
- :art: (drivers): Update QDAC
- :sparkles: (spikes): Add lk_qdac

2022-07-20 13:26 UTC, YannLocatelli requested changes
Quelques requêtes pour la clarté et un résultat un peu étonnant à expliquer.

Sinon tout est très bien en guise de spike pour montrer comment ça s'utilise, c'est bien 👍

2022-07-20 13:26 UTC, YannLocatelli commented on spikes/lk_qdac/main.cpp
> +		log_info("\n");
Je propose quelque chose de plus condensé encore: 
```suggestion
		log_info("================= Channel %d ================= ", ch);
		data = dac.read(ch);
		log_info("Input Registers === Data: %x", data);
		data = dac.read(ch, true);
		log_info("EEPROM Memory ===== Data: %x", data);
```

2022-07-20 13:26 UTC, YannLocatelli commented on spikes/lk_qdac/main.cpp
> +	log_info("Print !\n");
N'est pas vraiment utile ici :)
```suggestion
```

2022-07-20 13:26 UTC, YannLocatelli commented on spikes/lk_qdac/main.cpp
> +	dac.writeAllChannels(0x0000, true);
Autre détails marquant avec cette ligne, c'est qu'on inscrit `0x0000` pour chaque channel et que après on obtient

```
000:00:01.002 [INFO] [main.cpp:32] printInputRegistersAndMemory > ================= Channel 0 ================= 
000:00:01.005 [INFO] [main.cpp:34] printInputRegistersAndMemory > Input Registers === Data: 0
000:00:01.007 [INFO] [main.cpp:36] printInputRegistersAndMemory > EEPROM Memory ===== Data: fff
000:00:01.007 [INFO] [main.cpp:32] printInputRegistersAndMemory > ================= Channel 1 ================= 
000:00:01.010 [INFO] [main.cpp:34] printInputRegistersAndMemory > Input Registers === Data: 0
000:00:01.013 [INFO] [main.cpp:36] printInputRegistersAndMemory > EEPROM Memory ===== Data: fff
000:00:01.013 [INFO] [main.cpp:32] printInputRegistersAndMemory > ================= Channel 2 ================= 
000:00:01.016 [INFO] [main.cpp:34] printInputRegistersAndMemory > Input Registers === Data: 0
000:00:01.019 [INFO] [main.cpp:36] printInputRegistersAndMemory > EEPROM Memory ===== Data: fff
000:00:01.019 [INFO] [main.cpp:32] printInputRegistersAndMemory > ================= Channel 3 ================= 
000:00:01.022 [INFO] [main.cpp:34] printInputRegistersAndMemory > Input Registers === Data: 0
000:00:01.025 [INFO] [main.cpp:36] printInputRegistersAndMemory > EEPROM Memory ===== Data: fff
```

Pourquoi `fff` pour la mémoire et pas 0 comme pour l'input registers?

2022-07-21 07:53 UTC, YannLocatelli commented on spikes/lk_qdac/main.cpp
> +auto dac	 = CoreQDACMCP4728 {corei2c, 0xC0};
Même résultat pour l'autre DAC avec l'adresse `0xC2`?

2022-07-21 09:51 UTC, YannLocatelli approved these changes
Reste à corriger les 2 code smells et c'est bon pour moi 👌

2022-08-18 10:56 UTC, ladislas approved these changes
LGTM 👍

2022-08-19 19:21 UTC, merged