hugo/feature/Add ReinforcerKit
leka/LekaOS pull request #980
Opened 2022-08-25 18:47 UTC by HPezz

- :sparkles: (libs): Add ReinforcerKit
- :white_check_mark: (tests): Add ReinforcerKit_test.cpp
- :fire: (behavior): Remove Reinforcers from BehaviorKit
- :art: (commandkit): Update ReinforcerCommand
- :art: (os): Update OS with ReinforcerKit

2022-09-01 14:47 UTC, ladislas requested changes
LGTM 👍 modulo deux trois changements :)

2022-09-01 14:47 UTC, ladislas commented on libs/ReinforcerKit/include/ReinforcerKit.h
> +};
ça met le directement dans `class ReinforcerKit`

comme ça après tu as `ReinforcerKit::Reinforcer::Fire`

sinon il est dans le global namespace et c'est pas terrible.

2022-09-01 14:47 UTC, ladislas commented on libs/ReinforcerKit/source/ReinforcerKit.cpp
> +	}
petit switch là plutôt que if/else, beaucoup plus clean ;)

2022-09-01 14:47 UTC, ladislas commented on libs/ReinforcerKit/source/ReinforcerKit.cpp
> +	}
pas plus simple ça?

```suggestion
	run(default_reinforcer);
```

2022-09-01 14:47 UTC, ladislas commented on libs/ReinforcerKit/include/ReinforcerKit.h
> +	Reinforcer default_reinforcer = Reinforcer::BlinkGreen;
```suggestion
	Reinforcer _default_reinforcer = Reinforcer::BlinkGreen;
```

2022-09-02 08:14 UTC, YannLocatelli approved these changes
Pas grand chose à dire, c'est bon pour moi :)

2022-09-02 08:14 UTC, YannLocatelli commented on spikes/lk_command_kit/main.cpp
> -	behaviorkit.stop();
Pourquoi l'avoir retiré?

2022-09-02 08:14 UTC, YannLocatelli commented on libs/ReinforcerKit/include/ReinforcerKit.h
> +	void playRainbow();
`play` ou `run`? Ca serait cohérent avec le run de la ligne 34

```suggestion
	void runBlinkGreen();
	void runSpinBlink();
	void runFire();
	void runSprinkles();
	void runRainbow();
```

2022-09-02 08:23 UTC, YannLocatelli commented on libs/ReinforcerKit/source/ReinforcerKit.cpp
> +	switch (reinforcer) {
Suggestion un peu barbare, avoir un run qui prend en paramètre un Reinforcer en pointeur et s'il est nul de pouvoir lancer le renforçateur par défaut.

```suggestion
void ReinforcerKit::run(const Reinforcer *reinforcer = nullptr)
{
	auto selected_reinforcer = *reinforcer == nullptr ? _default_reinforcer : *reinforcer
	switch (selected_reinforcer) {
```

---

Ca permettrait de l'extérieur de simplifier encore plus les choses en ayant uniquement que `setDefaultReinforcer` 
 et `run` en fonctions d'appels de ReinforcerKit plutôt que de se dire "si je ne sais pas quel renforçateur appeler, il faut appeler une autre fonction"

2022-09-05 13:17 UTC, ladislas approved these changes
thanks! 👍

2022-09-05 17:24 UTC, merged