:art: (rfidkit): Add getCallback() func in RFIDKit
leka/LekaOS pull request #984
Opened 2022-08-30 14:43 UTC by HPezz

2022-08-30 21:41 UTC, ladislas requested changes
simple et clair! 👍 

il me manque juste un test avec un vrai callback, `nullptr` c'est trop facile ;)

2022-08-30 21:41 UTC, ladislas commented on libs/RFIDKit/tests/RFIDKit_test.cpp
> +TEST_F(RFIDKitTest, getCallback)
```suggestion
TEST_F(RFIDKitTest, getCallbackNullptr)
```

2022-08-31 13:13 UTC, YannLocatelli approved these changes

2022-08-31 21:44 UTC, ladislas approved these changes
j'approve aussi pour avancer mais j'aimerais qu'on puisse tester avec des mock callback

2022-08-31 21:44 UTC, merged