hugo/feature/Update GameKit and add first Game
leka/LekaOS pull request #985
Opened 2022-08-30 14:49 UTC by HPezz

- :art: (GameKit): Update GameKit
- :sparkles: (sm): Add SMAutonomousGames
- :dizzy: (game): Add DisplayTag game

2022-08-30 21:48 UTC, ladislas requested changes
LGTM 👍 

modulo les quelques suggestions et le naming de la state machine

2022-08-30 21:48 UTC, ladislas commented on libs/GameKit/source/games/DisplayTags.cpp
> +}
juste aérer un peu

```suggestion
void DisplayTags::start()
{
	_videokit.displayImage("fs/home/img/system/robot-misc-robot-misc-screen_empty_white.jpg");
	
	_backup_callback			  = _rfidkit.getCallback();
	
	auto on_tag_detected_callback = [this](const MagicCard &card) {
		if (card == MagicCard::remote_standard) {
			stop();
		} else {
			snprintf(path.data(), path.size(), "fs/home/img/id/00%x.jpg", card.getId());
			_videokit.displayImage(path.data());
		}
	};
	
	_rfidkit.onTagActivated(on_tag_detected_callback);
}
```

2022-08-30 21:48 UTC, ladislas commented on libs/GameKit/include/SMAutonomousGame.h
> +}	// namespace sm::event
```suggestion
namespace sm::event {

	struct start_game {
	};
	struct stop_game {
	};

}	// namespace sm::event
```

2022-08-30 21:48 UTC, ladislas commented on libs/GameKit/include/SMAutonomousGame.h
> +struct SMAutonomousGame {
```suggestion
struct AutonomousGamesStateMachine {
```

ou alors mettre dans un namespace `autonomous_games`

2022-08-30 21:48 UTC, ladislas commented on libs/GameKit/include/SMAutonomousGame.h
> +struct SMAutonomousGame {
et changer le nom du fichier aussi

2022-08-30 21:48 UTC, ladislas commented on libs/GameKit/include/SMAutonomousGame.h
> +struct SMAutonomousGame {
ou alors GameKitStateMachine si la logique est dans game kit

2022-08-30 21:48 UTC, ladislas commented on libs/GameKit/include/SMAutonomousGame.h
> +			, sm::state::playing_game + event<sm::event::stop_game>   = sm::state::idle
```suggestion
			* sm::state::idle         + event<sm::event::start_game> = sm::state::playing_game
			, sm::state::playing_game + event<sm::event::stop_game>  = sm::state::idle
```

2022-08-31 12:26 UTC, ladislas requested changes
merci beaucoup pour le renaming! 👍 

LGTM modulo quelques changements :)

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/include/ActivityKit.h
> +};
format

```suggestion
#pragma once

#include <unordered_map>

#include "Activity.h"
#include "MagicCard.h"

namespace leka {

class ActivityKit
{
  public:
	explicit ActivityKit() = default;

	void registerActivities(std::unordered_map<MagicCard, interface::Activity> const &activities);
	
	void start(const MagicCard &card);
	void stop();

  private:
	interface::Activity *_activity = nullptr;
	std::unordered_map<MagicCard, interface::Activity> _activities {};
};
```

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/include/ActivityKit.h
> +	interface::Activity *_activity = nullptr;
```suggestion
	interface::Activity *_current_activity = nullptr;
```

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/include/ActivityKit.h
> +	std::unordered_map<MagicCard, interface::Activity> _activities {};
ici plutôt un pointeur :) 

```suggestion
	std::unordered_map<MagicCard, interface::Activity*> _activities {};
```

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/source/ActivityKit.cpp
> +void ActivityKit::registerActivities(std::unordered_map<MagicCard, interface::Activity> const &activities)
```suggestion
void ActivityKit::registerActivities(std::unordered_map<MagicCard, interface::Activity*> const &activities)
```

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/source/ActivityKit.cpp
> +void ActivityKit::registerActivities(std::unordered_map<MagicCard, interface::Activity> const &activities)
le `const` généralement on le met à gauche nous

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/include/ActivityKit.h
> +	std::unordered_map<MagicCard, interface::Activity> _activities {};
ça évite de copier les activities dans le map et ça gagne de l'espace.

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/source/ActivityKit.cpp
> +	_activity = &_activities.at(card);
pas besoin du `&` avec le pointeur

```suggestion
	_current_activity = _activities.at(card);
```

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/source/ActivityKit.cpp
> +	_activity->start();
format

```suggestion
	}
	
	_activity->start();
```

2022-08-31 12:26 UTC, ladislas commented on libs/ActivityKit/source/ActivityKit.cpp
> +	}
ce check là est inutile parce qu'avec le map ça n'arrivera pas.

avec `map.at(key)` tu as un bound check, donc si la clé n'existe pas tu auras une erreur et ça plantera.

tu peux faire

```suggestion
	stop();
	
	if (auto activity_not_available = !_activities.contains(card); activity_not_available) {
		_current_activity == nullptr;
		return;
	}
	
	_current_activity = _activities.at(card);
	
	_activity->start();
}
```

2022-08-31 13:27 UTC, YannLocatelli reviewed
Reste la validation sur robot

2022-08-31 13:27 UTC, YannLocatelli commented on libs/ActivityKit/include/ActivityKit.h
> +class ActivityKit
Pas de backup_callback ici du coup?

2022-08-31 13:27 UTC, YannLocatelli commented on libs/ActivityKit/include/Activity.h
> +class Activity
Pourquoi cette interface est ici est non pas dans le dossier `include/interface`?

2022-08-31 13:27 UTC, YannLocatelli commented on libs/ActivityKit/source/activities/DisplayTags.cpp
> +	_videokit.displayImage("fs/home/img/system/robot-misc-robot-misc-screen_empty_white.jpg");
Juste une note pour plus tard: Ne pas avoir le path brut et permettre soit de mettre le nom du fichier, soit de récupérer depuis un enum le fichier associé afin d'être sûr qu'il existe

2022-08-31 21:40 UTC, ladislas commented on libs/ActivityKit/include/activities/DisplayTags.h
> +	std::array<char, 32> path = {};
```suggestion
	std::array<char, 32> _path_buffer = {};
```

2022-08-31 21:49 UTC, ladislas commented on libs/ActivityKit/include/ActivityKit.h
> +class ActivityKit
je me suis posé la question aussi.

si on le fait, ça fait que ActivityKit dépend de RFIDKit et est-ce qu'on veut ça ou pas?

à l'inverse ça veut dire que toutes les activities qui ont du RFID doivent penser à sauver le callback, ce qui est pas terrible

la solution transverse serait d'avoir une `interface::RFIDActivity` qui hérite de `interface::Activity` et qui donne une implémentation toute faite de la sauvegarde du call back dans le ctor et dtor par exemple

2022-09-01 15:08 UTC, ladislas commented on libs/ActivityKit/source/activities/DisplayTags.cpp
> +			snprintf(_path_buffer.data(), _path_buffer.size(), "fs/home/img/id/00%x.jpg", card.getId());
ici le format n'est pas évolutif.

si tu as `0x0100` ça marche déjà plus.

il faut un truc du genre:

```suggestion
			snprintf(_path_buffer.data(), _path_buffer.size(), "fs/home/img/id/0x%.4X.jpg", card.getId());
```

2022-09-01 15:08 UTC, ladislas commented on libs/ActivityKit/source/activities/DisplayTags.cpp
> +			snprintf(_path_buffer.data(), _path_buffer.size(), "fs/home/img/id/00%x.jpg", card.getId());
`x` si minuscule et `X` si majuscule dans les noms de fichiers

2022-09-01 15:09 UTC, ladislas commented on libs/ActivityKit/tests/ActivityKit_test.cpp
> +	mock::Activity mock_new_activity {};
```suggestion
	mock::Activity mock_activity_0 {};
	mock::Activity mock_activity_1 {};
```

2022-09-01 15:09 UTC, ladislas commented on libs/ActivityKit/tests/ActivityKit_test.cpp
> +		{MagicCard::number_1, &mock_new_activity},
```suggestion
		{MagicCard::number_0, & mock_activity_0},
		{MagicCard::number_1, & mock_activity_1},
```

2022-09-01 15:10 UTC, ladislas commented on libs/RFIDKit/include/MagicCard.h
> +}	// namespace std
```suggestion

// ? Make MagicCard std::hash compatible for use in associative containers (i.e. std::unordered_map)
namespace std {
template <>
struct hash<leka::MagicCard> {
	auto operator()(const leka::MagicCard &card) const -> size_t { return hash<int>()(card.getId()); }
};
}	// namespace std
```

2022-09-01 22:41 UTC, closed without merging