hugo/feature/Update RC SM and OS to Gamekit
leka/LekaOS pull request #986
Opened 2022-08-30 14:50 UTC by HPezz

- :art: (rc & sm): Update RC & SM to GameKit
- :white_check_mark: (tests): Update tests RC & SM
- :art: (os): Update OS to GameKit

2022-08-30 21:54 UTC, ladislas requested changes
premier passage, ça me semble bien mais je revois demain de nouveau :)

2022-08-30 21:54 UTC, ladislas commented on app/os/main.cpp
> +			}
est-ce que tu n'as pas un risque que la transition soit pas finie quand le deuxième if arrive et que tu aies pas de start?

je trouve les 2 if qui se suivent bizarres, je mettrais dans des lambdas, au moins le deuxième if

2022-08-30 21:54 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +		_behaviorkit.chooseActivity();
ça ça irait pas mieux dans gamekit?

2022-08-30 21:54 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	void startRfidActivityBehavior() final
le nom avec le rfid est pas très clair, `startChooseAutonomousActivityBehavior` par exemple

mais maintenant on a `games` et `activities`, il faut homogénéiser je pense pour éviter les confusions

activities est peut être mieux

2022-08-31 08:09 UTC, ladislas requested changes
petits changements de naming

2022-09-02 08:29 UTC, YannLocatelli commented
La branche de base a été closed, est-ce que tu peux repointer sur une branche en cours pour que les commits soient à jour? Merci~

2022-09-02 09:49 UTC, YannLocatelli reviewed
Merci pour tout le travail réalisé

2022-09-02 09:49 UTC, YannLocatelli commented on app/os/main.cpp
> +			activitykit.start(card);
**WARNING**

J'avoue que ces deux lignes me troubles.

Sortir la state machine du robot controller et utiliser activitykit dans deux fichiers à la fois.

J'ai l'impression qu'on commence à emmêler les choses dans tous les sens et que ça va devenir difficile de savoir qui fait quoi et jusqu'où

2022-09-02 09:49 UTC, YannLocatelli commented on app/os/main.cpp
> +			controller.stopStartAutonomousActivity();
Je me demandais si c'était une fonction, il s'agit aussi d'un déclenchement d'event comme au dessus. On peut rajouter le mot `raise`?

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/StateMachine.h
> +	};
Je ne comprends pas cet event, pourquoi ce n'est pas plutôt `start_autonomous_activity`?

Il s'agit de lancer les activités autonomes suite à cet événement et non pas de réagir à l'événement qu'à été la lancement des activités.

Si on veut être plus précis on peut avoir `autonomous_activity_requested`

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/StateMachine.h
> +			, sm::state::idle     + event<sm::event::autonomous_activity_did_start>                                        = sm::state::autonomous_activity
C'est un peu nul ce que je vais dire mais.... il manque un espace et c'est pas aligné sur celui-ci et les suivants 😅

```suggestion
			, sm::state::idle     + event<sm::event::charge_did_start> [sm::guard::is_charging {}]                          = sm::state::charging
			, sm::state::idle     + event<sm::event::emergency_stop>                                                        = sm::state::emergency_stopped
			, sm::state::idle     + event<sm::event::autonomous_activity_did_start>                                         = sm::state::autonomous_activity
```

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/StateMachine.h
> +
Est-ce que le choose et le behavior sont importants? Est-ce qu'on ne peut pas avoir plus simplement

```suggestion
	struct start_autonomous_activity {
		auto operator()(irc &rc) const { rc.startAutonomousActivity(); }
	};

	struct stop_autonomous_activity {
		auto operator()(irc &rc) const { rc.stopAutonomousActivity(); }
	};

```

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
> +		_behaviorkit.chooseActivity();
J'ai buté sur la compréhension de cette ligne. J'ai pensé que c'était là où se choisissait l'activité, mais non c'est juste afficher sur l'écran le menu

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
> +		_behaviorkit.chooseActivity();
Du coup ça porte encore plus à confusion puisqu'après avoir compris ça, on se demande à quel moment on choisit l'activité réellement.

Je suis confus.

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/RobotController.h
> +	void stopStartAutonomousActivity() { raise(system::robot::sm::event::autonomous_activity_did_start {}); }
Question tout à fait naïve, pourquoi il y a `stop` dans le nom?

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateCharging.cpp
> +TEST_F(RobotControllerTest, stateChargingEventAutonomousActivityTransition)
Naming

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/include/StateMachine.h
> +			, sm::state::autonomous_activity + event<sm::event::autonomous_activity_did_start>                                                 = sm::state::autonomous_activity
En lisant les tests, je me suis aperçu de l'absurdité de certains guard: tout ce qui est charge peut-être retiré car dans l'état de `autonomous_activity` on est nécessairement hors charge.

Le double checkup n'est que pour la transition vers la charge.

```suggestion
			, sm::state::autonomous_activity + event<sm::event::command_received> [sm::guard::is_connected {}]                                  = sm::state::working
			, sm::state::autonomous_activity + event<sm::event::ble_connection>                                                                 = sm::state::working
			, sm::state::autonomous_activity + event<sm::event::charge_did_start> [sm::guard::is_charging {}]                                   = sm::state::charging
			, sm::state::autonomous_activity + event<sm::event::emergency_stop>                                                                 = sm::state::emergency_stopped
			, sm::state::autonomous_activity + event<sm::event::autonomous_activity_did_start>                                                  = sm::state::autonomous_activity
```

---

Attention à ne pas faire des copier-coller trop rapidement, surtout à partir d'un cas très particulier qu'est l'emergency stop

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/tests/StateMachine_test.cpp
> +}
Grâce à test, j'ai pu me poser réellement la question sur la pertinence de faire un check sur charging dans l'état d'activité autonome, comme quoi ça marche! 👍😂

En bref, je m'attendais à quelque chose de plus simple, c'est pour ça que j'ai tiqué quand j'ai vu que c'était bien plus que ce à quoi je m'attendais

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateIdle.cpp
> +	rc.state_machine.set_current_states(lksm::state::idle);
Well done

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateAutonomousGames.cpp
> +	EXPECT_CALL(mock_motor_right, stop).InSequence(on_game_exit_sequence);
Il ne manque pas les LEDs qui s'éteignent dans le `on_game_exit_sequence`?

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateAutonomousGames.cpp
> +	EXPECT_CALL(mock_videokit, playVideoOnce).Times(1);
A quelle(s) séquence(s) sont reliés ces expect calls ?

2022-09-02 09:49 UTC, YannLocatelli commented on libs/RobotKit/tests/RobotController_test_stateAutonomousGames.cpp
> +}
Ah, je m'attendais à un lcd_on aussi...

C'est un retour au menu principal?

2022-09-02 16:35 UTC, HPezz commented on libs/RobotKit/tests/RobotController_test_stateAutonomousGames.cpp
> +}
Yes

2022-09-05 21:16 UTC, ladislas requested changes
1er passage avant d'en causer demain :) 
bon boulot! c'est très cool 👍

2022-09-05 21:16 UTC, ladislas commented on app/os/main.cpp
> +#include "boost/sml.hpp"
toujours besoin de ça?

2022-09-05 21:16 UTC, ladislas commented on app/os/main.cpp
> +}	// namespace activities
pour faire comme les commandes :

```suggestion
namespace activity {

	namespace internal {
	
		auto display_tag = leka::activity::DisplayTags(rfidkit, display::videokit);
	
	}

	const std::unordered_map<MagicCard, interface::Activity *> list {{MagicCard::number_10, &display_tag},};

}	// namespace activities
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	void startAutonomousActivity() final
de même que pour en dessous, le nom n'est pas très clair. en soi on ne commence pas une activité ici, on se met dans le mode autonomous activities

```suggestion
	void startAutonomousActivitiesMode() final
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +		_behaviorkit.chooseActivity();
je suis d'accord avec @YannLocatelli -- le nom porte un peu à confusion.

je dirai 

```suggestion
		_behaviorkit.displayAutonomousActivitiesPrompt();
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	void stopAutonomousActivity() final
pareil dans l'autre sens

```suggestion
	void stopAutonomousActivitiesMode() final
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/RobotController.h
> +	void raiseAutonomousActivity() { raise(system::robot::sm::event::autonomous_activity_requested {}); }
pareil ici : "raise autonomous activity" ça veut pas dire grand chose en anglais.

```suggestion
	void raiseAutonomousActivitiesModeRequested() { raise(system::robot::sm::event::autonomous_activity_requested {}); }
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	struct autonomous_activity_requested {
```suggestion
	struct autonomous_activities_mode_requested {
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	inline auto autonomous_activity = boost::sml::state<class autonomous_activity>;
```suggestion
	inline auto autonomous_activities = boost::sml::state<class autonomous_activity>;
```

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/include/StateMachine.h
> +	};
mode aussi

2022-09-05 21:16 UTC, ladislas commented on libs/RobotKit/tests/StateMachine_test.cpp
> +}
il commence à y avoir trop de tests dans le même fichier, il faudrait séparer

2022-09-06 22:25 UTC, merged